/* Functional ERP records for the local workspace. No production account provisioning. */
const ERP_MODULES={
 courses:{title:'Course Management',fields:[['code','Course code'],['title','Course title'],['category','Category'],['duration','Duration'],['fee','Course fee (NGN)','number'],['status','Status',['Draft','Published','Archived']]]},
 students:{title:'Learner Records',fields:[['name','Full name'],['email','Email','email'],['phone','Phone','tel'],['program','Programme'],['status','Status',['Active','Inactive']],['payment','Payment',['Unpaid','Part Paid','Paid']]]},
 staff:{title:'Staff Directory',note:'Personnel records only. Creating a record does not create a login account.',fields:[['name','Full name'],['email','Email','email'],['role','Role',['Admin','Instructor','Support']],['specialization','Specialization'],['status','Status',['Active','Inactive']]]},
 admissions:{title:'Admissions',fields:[['name','Applicant name'],['email','Email','email'],['phone','Phone','tel'],['program','Programme'],['status','Status',['New','Under review','Accepted','Declined']],['date','Application date','date']]},
 assignments:{title:'Assignments',fields:[['title','Assignment title'],['courseId','Course','courses'],['instructions','Instructions','textarea'],['date','Due date','date'],['status','Status',['Draft','Published','Closed']]]},
 quizzes:{title:'Assessment Register',note:'Plan assessments here; record graded scores in Results. Online quiz delivery is not enabled.',fields:[['title','Assessment title'],['courseId','Course','courses'],['type','Type',['Quiz','Exam','Practical']],['date','Assessment date','date'],['passMark','Pass mark (%)','number'],['status','Status',['Draft','Published','Closed']]]},
 attendance:{title:'Attendance',fields:[['studentId','Learner','students'],['courseId','Course','courses'],['date','Class date','date'],['status','Attendance',['Present','Absent','Late','Excused']]]},
 timetable:{title:'Class Timetable',fields:[['courseId','Course','courses'],['instructor','Instructor'],['date','Class date','date'],['start','Start time','time'],['end','End time','time'],['mode','Mode',['Classroom','Online','Hybrid']],['location','Venue or meeting URL']]},
 results:{title:'Results',fields:[['studentId','Learner','students'],['courseId','Course','courses'],['title','Assessment'],['score','Score (%)','number'],['status','Status',['Draft','Published']]]},
 certificates:{title:'Certificates',note:'Issue only after confirming completion and published passing results. Verification is local to this workspace.',fields:[['studentId','Learner','students'],['courseId','Course','courses'],['date','Issue date','date'],['status','Status',['Issued','Revoked']]]},
 invoices:{title:'Invoices & Balances',fields:[['studentId','Learner','students'],['courseId','Course','courses'],['amount','Amount due (NGN)','number'],['date','Due date','date']]},
 payments:{title:'Payment Records',note:'Record payments, then confirm verified receipts. Only verified payments can allocate a course.',fields:[['studentId','Learner','students'],['courseId','Course','courses'],['invoiceId','Invoice (optional)','invoices'],['amount','Amount received (NGN)','number'],['date','Payment date','date'],['method','Method',['Bank transfer','Cash','Card']],['status','Status',['Pending','Verified','Rejected']],['description','Reference / description']]},
 announcements:{title:'Announcements',fields:[['title','Title'],['message','Message','textarea'],['date','Publication date','date']]}
};
const erpDate=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Lagos'});
function erpItems(key){return data[key]||(data[key]=[])}
function erpLookup(key,id){const r=(data[key]||[]).find(x=>String(x.id||x.code)===String(id));return r?(r.name||r.title||r.reference):id||'—'}
function erpAudit(action,module,id){erpItems('audit').unshift({id:crypto.randomUUID(),date:new Date().toISOString(),actor:currentUser?.name||'Preview',action,module,record:id});data.audit=data.audit.slice(0,1000);persist()}
function erpAllowed(key){return ['admin','super_admin'].includes(currentUser?.role)||(['assignments','quizzes','attendance','timetable','results','announcements'].includes(key)&&currentUser?.role==='instructor')}
function erpCell(row,field){const [key,label,type]=field;let v=row[key];if(type==='students'||type==='courses'||type==='invoices')v=erpLookup(type,v);if(key==='amount'||key==='fee')return ethanMoney(v);return escHtml(String(v??'—'))}
function erpCsv(name,rows){const headers=[...new Set(rows.flatMap(r=>Object.keys(r)))];const quote=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@-]/,"'$&")+'"';erpDownload(name+'.csv',[headers,...rows.map(r=>headers.map(h=>r[h]))].map(r=>r.map(quote).join(',')).join('\r\n'),'text/csv')}
function erpDownload(name,content,type){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function renderErpModule(key){
 const cfg=ERP_MODULES[key],allowed=erpAllowed(key);let rows=erpItems(key);
 if(!allowed){const mine=(data.students||[]).find(s=>s.email===currentUser.email);rows=rows.filter(r=>r.studentId&&r.studentId===mine?.id&&(key!=='results'||r.status==='Published'));}
 const fields=cfg.fields;
 $('#content').innerHTML=pageHead(cfg.title,cfg.note||'Create, review, edit and export academy records.',`<div><button class="secondary-btn" id="erpExport">Export CSV</button> ${allowed?'<button class="primary-btn" id="erpAdd">+ Add Record</button>':''}</div>`)+
 `<section class="card"><label>Search records<input id="erpFilter" type="search" placeholder="Type to filter..."></label><div class="table-wrap"><table class="data-table"><thead><tr><th>Reference</th>${fields.map(f=>`<th>${f[1]}</th>`).join('')}${key==='invoices'?'<th>Paid</th><th>Balance</th><th>Invoice status</th>':''}<th>Actions</th></tr></thead><tbody id="erpRows"></tbody></table></div></section>`;
 let currentListPage=0;const pageSize=20;let searchQuery='';
 const draw=q=>{searchQuery=q;$('#erpRows').innerHTML=rows.filter(r=>(JSON.stringify(r)+' '+fields.map(f=>erpCell(r,f)).join(' ')).toLowerCase().includes(q)).slice(currentListPage*pageSize,(currentListPage+1)*pageSize).map(r=>{const paid=key==='invoices'?erpInvoicePaid(r):0;return `<tr><td>${escHtml(r.reference||r.id)}</td>${fields.map(f=>`<td>${erpCell(r,f)}</td>`).join('')}${key==='invoices'?`<td>${ethanMoney(paid)}</td><td>${ethanMoney(Math.max(0,Number(r.amount)-paid))}</td><td>${erpInvoiceBalance(r)===0?'Paid':r.date<erpDate()?'Overdue':paid>0?'Part Paid':'Unpaid'}</td>`:''}<td>${allowed?`${key==='students'?`<button class="text-btn" data-profile="${r.id}">Summary</button>`:''}${key==='admissions'&&r.status==='Accepted'?`<button class="text-btn" data-convert="${r.id}">Create Learner</button>`:''}<button class="text-btn" data-edit="${r.id}">Edit</button> <button class="text-btn" data-remove="${r.id}">Delete</button>`:''}${key==='certificates'||key==='payments'||key==='invoices'?` <button class="text-btn" data-print="${r.id}">Print</button>`:''}${key==='payments'&&allowed&&r.status==='Verified'?` <button class="text-btn" data-allocate="${r.id}">Allocate Course</button>`:''}</td></tr>`}).join('')||`<tr><td colspan="20">No records found.</td></tr>`;
 $$('[data-profile]').forEach(b=>b.onclick=()=>erpLearnerSummary(b.dataset.profile));$$('[data-convert]').forEach(b=>b.onclick=()=>{try{erpConvertAdmission(b.dataset.convert);renderErpModule(key);alert('Learner record created. This does not create a login account.');}catch(err){alert(err.message)}});
 $$('[data-edit]').forEach(b=>b.onclick=()=>erpEdit(key,b.dataset.edit));$$('[data-remove]').forEach(b=>b.onclick=()=>{try{erpRecycle(key,b.dataset.remove);renderErpModule(key)}catch(err){alert(err.message)}});
 $$('[data-print]').forEach(b=>b.onclick=()=>erpPrint(key,rows.find(r=>r.id===b.dataset.print)));
 $$('[data-allocate]').forEach(b=>b.onclick=()=>{try{erpAllocatePayment(b.dataset.allocate);alert('Course allocated. No additional payment was recorded.');}catch(err){alert(err.message)}});}; const pager=document.createElement('div');pager.className='erp-pagination';pager.innerHTML='<button class="secondary-btn" id="erpPrev">Previous</button><span id="erpPage"></span><button class="secondary-btn" id="erpNext">Next</button>';$('#content .card').append(pager);const pageDraw=()=>{draw(searchQuery);const count=rows.filter(r=>(JSON.stringify(r)+' '+fields.map(f=>erpCell(r,f)).join(' ')).toLowerCase().includes(searchQuery)).length;$('#erpPage').textContent='Page '+(currentListPage+1)+' · '+count+' records';$('#erpPrev').disabled=currentListPage===0;$('#erpNext').disabled=(currentListPage+1)*pageSize>=count;};$('#erpPrev').onclick=()=>{if(currentListPage>0){currentListPage--;pageDraw()}};$('#erpNext').onclick=()=>{currentListPage++;pageDraw()};pageDraw();$('#erpFilter').oninput=e=>{currentListPage=0;searchQuery=e.target.value.toLowerCase();pageDraw()};$('#erpExport').onclick=()=>erpCsv('ETHAN-'+key,rows);if(allowed)$('#erpAdd').onclick=()=>erpEdit(key);
}
function erpEdit(key,id){
 if(!erpAllowed(key))return;const cfg=ERP_MODULES[key],old=erpItems(key).find(r=>r.id===id)||{};
 const fields=cfg.fields;const html=fields.map(([f,label,type])=>{const v=old[f]??(type==='date'?erpDate():'');let input;if(Array.isArray(type))input=`<select id="f-${f}">${type.map(o=>`<option ${v===o?'selected':''}>${escHtml(o)}</option>`).join('')}</select>`;else if(type==='students'||type==='courses'||type==='invoices')input=`<select id="f-${f}"><option value="">Select ${label}</option>${erpItems(type).map(r=>`<option value="${escHtml(r.id||r.code)}" ${v===(r.id||r.code)?'selected':''}>${escHtml(r.name||r.title||r.reference)}${type==='invoices'?' · '+escHtml(erpLookup('students',r.studentId))+' · '+ethanMoney(r.amount):''}</option>`).join('')}</select>`;else if(type==='textarea')input=`<textarea id="f-${f}" rows="4">${escHtml(v)}</textarea>`;else input=`<input id="f-${f}" type="${type||'text'}" value="${escHtml(String(v))}" ${type==='number'?'min="0" step="0.01"':''}>`;return `<label>${label}${input}</label>`}).join('');
 showModal(id?'Edit Record':'Add Record',cfg.title,html,()=>{
 const row={...old,id:old.id||crypto.randomUUID(),reference:old.reference||'EDA-'+key.toUpperCase().slice(0,4)+'-'+Date.now()};
 for(const [f,label,type] of fields){let v=$('#f-'+f).value.trim();if(!v&&f==='invoiceId'){row[f]='';continue;}if(!v)return alert('Complete '+label+'.');if(type==='number'){v=Number(v);if(!Number.isFinite(v)||v<0||(f==='amount'&&v<=0))return alert('Enter a valid '+label+'.');if((f==='score'||f==='passMark')&&v>100)return alert(label+' must be between 0 and 100.');}if(type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))return alert('Enter a valid email.');row[f]=v;}
 try{erpValidateRow(key,row);}catch(err){return alert(err.message);}
 if(key==='timetable'&&row.end<=row.start)return alert('End time must be after start time.');
 if(key==='attendance'&&erpItems(key).some(r=>r.id!==row.id&&r.studentId===row.studentId&&r.courseId===row.courseId&&r.date===row.date))return alert('Attendance already exists for this learner, course and date.');
 if(key==='courses'){row.published=row.status==='Published';row.progress=old.progress||0;if(erpItems(key).some(r=>r.id!==row.id&&r.code===row.code))return alert('Course code already exists.');}
 if(key==='students'){if(erpItems(key).some(r=>r.id!==row.id&&r.email.toLowerCase()===row.email.toLowerCase()))return alert('This learner email is already registered.');row.progress=old.progress||0;}
 if(key==='certificates'&&row.status==='Issued'&&!erpItems('results').some(r=>r.studentId===row.studentId&&r.courseId===row.courseId&&r.status==='Published'&&Number(r.score)>=60))return alert('Record a published passing result of at least 60% before issuing.');
 if(id)data[key]=data[key].map(r=>r.id===id?row:r);else data[key].push(row);erpAudit(id?'update':'create',key,row.id);closeModal();renderErpModule(key);
 });
}
function erpPrint(key,row){if(!row)return;const w=window.open('','_blank');if(!w)return alert('Allow pop-ups to print.');w.document.write(`<!doctype html><html><head><title>Ethan ${key}</title><style>body{font:16px Arial;padding:50px;color:#102a52}h1{border-bottom:3px solid #102a52;padding-bottom:20px}p{line-height:1.8}@media print{button{display:none}}</style></head><body><h1>ETHAN DIGITAL ACADEMY</h1><h2>${escHtml(ERP_MODULES[key].title)}</h2><p>Reference: ${escHtml(row.reference||row.id)}</p>${ERP_MODULES[key].fields.map(f=>`<p><strong>${f[1]}:</strong> ${erpCell(row,f)}</p>`).join('')}${key==='invoices'?`<p><strong>Verified payments:</strong> ${ethanMoney(erpInvoicePaid(row))}</p><p><strong>Outstanding balance:</strong> ${ethanMoney(erpInvoiceBalance(row))}</p>`:''}<p>Generated from the academy workspace. ${key==='payments'&&row.status!=='Verified'?'Payment has not been verified.':''}</p><button onclick="window.print()">Print / Save PDF</button></body></html>`);w.document.close()}
for(const key of ['admissions','invoices'])if(!adminNav.some(n=>n[0]===key))adminNav.push([key,'▤',ERP_MODULES[key].title]);
navByRole.super_admin=[...adminNav];navByRole.admin=adminNav;
const erpNavigateBase=navigate;
navigate=function(page){if(ERP_MODULES[page]){currentPage=page;$$('#sideNav .nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#pageTitle').textContent=ERP_MODULES[page].title;renderErpModule(page);return;}erpNavigateBase(page)};
renderStudents=()=>renderErpModule('students');renderStaff=()=>renderErpModule('staff');renderInstructors=()=>renderErpModule('staff');renderAssignments=()=>renderErpModule('assignments');renderQuizzes=()=>renderErpModule('quizzes');renderAttendance=()=>renderErpModule('attendance');renderTimetable=()=>renderErpModule('timetable');renderResults=()=>renderErpModule('results');renderCertificates=()=>renderErpModule('certificates');renderPayments=()=>renderErpModule('payments');renderAnnouncements=()=>renderErpModule('announcements');
renderReports=function(){const paid=erpItems('payments').filter(p=>p.status==='Verified').reduce((s,p)=>s+Number(p.amount),0),expenses=erpItems('expenses').reduce((s,p)=>s+Number(p.amount),0);$('#content').innerHTML=pageHead('Academy Reports','Totals calculated from workspace records.')+`<div class="stats-grid">${stat('Learners',data.students.length,'Registered records','▤')}${stat('Verified receipts',ethanMoney(paid),'Verified payments only','₦')}${stat('Expenses',ethanMoney(expenses),'Recorded costs','₦')}${stat('Net cash movement',ethanMoney(paid-expenses),'Receipts less expenses','₦')}</div><section class="card"><h3>Export Records</h3><div class="quick-grid">${Object.entries(ERP_MODULES).map(([k,v])=>`<button class="secondary-btn" data-export="${k}">${v.title} CSV</button>`).join('')}<button class="secondary-btn" data-export="audit">Activity Log CSV</button></div></section><section class="card"><h3>Recent Activity</h3>${erpItems('audit').slice(0,20).map(r=>`<p>${escHtml(r.date)} · ${escHtml(r.actor)} · ${escHtml(r.action)} · ${escHtml(r.module)}</p>`).join('')||'<p>No recorded activity.</p>'}</section>`;$$('[data-export]').forEach(b=>b.onclick=()=>erpCsv('ETHAN-'+b.dataset.export,erpItems(b.dataset.export)))};
const erpOperationsBase=renderOperations;
renderOperations=function(){erpOperationsBase();const section=document.createElement('section');section.className='card';section.innerHTML='<h3>Restore Workspace Backup</h3><p>Select a backup exported by this ERP. Restoration replaces current browser records after confirmation.</p><input id="erpRestore" type="file" accept="application/json,.json">';$('#content').append(section);$('#erpRestore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const backup=JSON.parse(await f.text());if(backup.app!=='Ethan Digital Academy ERP'||backup.version!==1||!backup.data||typeof backup.data!=='object'||Array.isArray(backup.data))throw Error('Select a valid Ethan ERP version 1 backup.');for(const key of ['students','courses','payments','enrolments'])if(!Array.isArray(backup.data[key]))throw Error('Backup is missing '+key+'.');if(Object.values(backup.data).some(v=>!Array.isArray(v)))throw Error('Invalid backup record collections.');if(!confirm('Replace all current workspace records with this backup?'))return;data=backup.data;erpAudit('restore','workspace','backup');renderOperations();alert('Backup restored.');}catch(err){alert(err.message)}}};
const erpSettingsBase=renderSettings;
renderSettings=function(){erpSettingsBase();const saved=JSON.parse(localStorage.getItem('ethan_academy_settings')||'null');if(saved){$('#academyNameSetting').value=saved.name||'';$('#academyWebsiteSetting').value=saved.website||'';}};

function table(headers,rows){return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${escHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
window.addEventListener('DOMContentLoaded',()=>{
 let changed=false;for(const k of Object.keys(ERP_MODULES))for(const r of erpItems(k))if(!r.id){r.id=r.code||crypto.randomUUID();changed=true;}if(changed)persist();
 if(currentUser){renderNav();navigate('dashboard');}
});
