/* v3: connected workflows within the local academy workspace. */
function erpInvoicePaid(invoice){return erpItems('payments').filter(p=>p.status==='Verified'&&p.invoiceId===invoice.id).reduce((sum,p)=>sum+Number(p.amount||0),0)}
function erpInvoiceBalance(invoice){return Math.max(0,Number(invoice.amount||0)-erpInvoicePaid(invoice))}
function erpValidateRow(key,row){
 for(const field of ERP_MODULES[key].fields){const [name,label,type]=field;if(['students','courses','invoices'].includes(type)&&row[name]){if(!erpItems(type).some(r=>String(r.id||r.code)===String(row[name])))throw Error('Select an existing '+label+'.');}}
 if(key==='attendance'&&erpItems(key).some(r=>r.id!==row.id&&r.studentId===row.studentId&&r.courseId===row.courseId&&r.date===row.date))throw Error('Attendance already exists for this learner, course and date.');
 if(key==='payments'&&row.invoiceId){const invoice=erpItems('invoices').find(i=>i.id===row.invoiceId);if(invoice.studentId!==row.studentId||invoice.courseId!==row.courseId)throw Error('The invoice must belong to the selected learner and course.');if(row.status==='Verified'){const otherPaid=erpItems('payments').filter(p=>p.id!==row.id&&p.invoiceId===invoice.id&&p.status==='Verified').reduce((s,p)=>s+Number(p.amount),0);if(otherPaid+Number(row.amount)>Number(invoice.amount)+0.001)throw Error('This payment exceeds the invoice balance. Split the receipt or leave it unassigned.');}}
 if(key==='invoices'){const old=erpItems('invoices').find(i=>i.id===row.id);if(old&&erpInvoicePaid(old)>0&&(row.studentId!==old.studentId||row.courseId!==old.courseId))throw Error('An invoice with verified payments cannot be moved to another learner or course.');if(Number(row.amount)<erpInvoicePaid(row))throw Error('Invoice total cannot be lower than verified receipts.');}
 if(key==='timetable'){if(erpItems(key).some(r=>r.id!==row.id&&r.date===row.date&&r.start<row.end&&r.end>row.start&&(r.instructor.toLowerCase()===row.instructor.toLowerCase()||r.location.toLowerCase()===row.location.toLowerCase())))throw Error('The instructor or venue already has an overlapping class.');}
}
function erpRecycle(key,id){
 if(!erpAllowed(key))throw Error('You do not have permission to remove this record.');const row=erpItems(key).find(r=>r.id===id);if(!row)throw Error('Record not found.');
 const used=(collection,field)=>erpItems(collection).some(r=>r[field]===id);
 if(key==='students'||key==='courses'){const field=key==='students'?'studentId':'courseId';if(['enrolments','attendance','results','certificates','payments','invoices'].some(k=>used(k,field))||(key==='courses'&&['assignments','quizzes','timetable'].some(k=>used(k,'courseId'))))throw Error('This record has linked academy history. Set it inactive or archived instead.');}
 if(key==='invoices'&&used('payments','invoiceId'))throw Error('This invoice has linked payments and cannot be removed.');
 if(key==='payments'&&row.status==='Verified')throw Error('Verified receipts cannot be removed. Review or correct the receipt first.');
 erpItems('trash').unshift({id:crypto.randomUUID(),module:key,record:structuredClone(row),removedAt:new Date().toISOString()});data[key]=data[key].filter(r=>r.id!==id);erpAudit('recycle',key,id);
}
function erpRestoreRecord(id){const item=erpItems('trash').find(r=>r.id===id);if(!item)throw Error('Recycled record not found.');if(!erpAllowed(item.module))throw Error('Access restricted.');if(erpItems(item.module).some(r=>r.id===item.record.id))throw Error('A record with this ID already exists.');erpValidateRow(item.module,item.record);if(item.module==='students'&&erpItems('students').some(r=>r.email.toLowerCase()===item.record.email.toLowerCase()))throw Error('A learner with this email already exists.');if(item.module==='courses'&&erpItems('courses').some(r=>r.code===item.record.code))throw Error('This course code already exists.');erpItems(item.module).push(item.record);data.trash=data.trash.filter(r=>r.id!==id);erpAudit('restore',item.module,item.record.id)}
function erpConvertAdmission(id){if(!erpAllowed('admissions'))throw Error('Access restricted.');const a=erpItems('admissions').find(r=>r.id===id);if(!a||a.status!=='Accepted')throw Error('Accept the application first.');if(a.studentId||erpItems('students').some(r=>r.email.toLowerCase()===a.email.toLowerCase()))throw Error('A learner already exists for this application or email.');const learner={id:crypto.randomUUID(),reference:'EDA-ST-'+Date.now(),name:a.name,email:a.email,phone:a.phone,program:a.program,status:'Active',payment:'Unpaid',progress:0,admissionId:a.id};erpItems('students').push(learner);a.studentId=learner.id;erpAudit('convert','admissions',a.id);return learner}
function erpAllocatePayment(id){if(!erpAllowed('payments'))throw Error('Access restricted.');const p=erpItems('payments').find(r=>r.id===id);if(!p||p.status!=='Verified')throw Error('Verify the receipt first.');const learner=erpItems('students').find(r=>r.id===p.studentId),course=erpItems('courses').find(r=>(r.id||r.code)===p.courseId);if(!learner||!course)throw Error('Learner or course is missing.');if(!erpItems('enrolments').some(e=>e.studentId===p.studentId&&e.courseId===p.courseId))data.enrolments.push({id:crypto.randomUUID(),studentId:p.studentId,courseId:p.courseId,courseCode:course.code,status:'active',allocatedAt:new Date().toISOString(),paymentId:p.id});learner.program=course.title;const total=erpItems('payments').filter(r=>r.studentId===p.studentId&&r.courseId===p.courseId&&r.status==='Verified').reduce((s,r)=>s+Number(r.amount),0);learner.payment=total>=Number(course.fee||0)?'Paid':'Part Paid';erpAudit('allocate','enrolments',p.id)}
function erpLearnerSummary(id){const s=erpItems('students').find(r=>r.id===id);if(!s)return;const mine=k=>erpItems(k).filter(r=>r.studentId===id);const receipts=mine('payments').filter(r=>r.status==='Verified').reduce((v,r)=>v+Number(r.amount),0);const balance=mine('invoices').reduce((v,r)=>v+erpInvoiceBalance(r),0);showModal(s.name,'Learner account summary',`<p>${escHtml(s.email)} · ${escHtml(s.phone||'')}</p><div class="stats-grid">${stat('Verified receipts',ethanMoney(receipts),'Recorded payments','₦')}${stat('Outstanding',ethanMoney(balance),'Invoice balances','₦')}${stat('Attendance',mine('attendance').length,'Class records','▤')}${stat('Courses',mine('enrolments').length,'Allocated programmes','▤')}</div><h3>Published Results</h3>${mine('results').filter(r=>r.status==='Published').map(r=>`<p>${escHtml(erpLookup('courses',r.courseId))} · ${escHtml(r.title)} · ${Number(r.score)}%</p>`).join('')||'<p>No published results.</p>'}`,()=>closeModal());$('#modalSave').textContent='Close'}
function erpMarkClass(courseId,date,statuses){if(!erpAllowed('attendance'))throw Error('Access restricted.');if(!erpItems('courses').some(c=>(c.id||c.code)===courseId))throw Error('Select a valid course.');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Select a class date.');for(const [studentId,status] of Object.entries(statuses)){if(!erpItems('students').some(s=>s.id===studentId)||!['Present','Absent','Late','Excused'].includes(status))throw Error('Invalid attendance selection.');}
 for(const [studentId,status] of Object.entries(statuses)){const old=erpItems('attendance').find(r=>r.studentId===studentId&&r.courseId===courseId&&r.date===date);if(old)old.status=status;else data.attendance.push({id:crypto.randomUUID(),reference:'EDA-ATT-'+Date.now()+'-'+studentId.slice(0,6),studentId,courseId,date,status});}erpAudit('mark-class','attendance',courseId)}
function erpBulkAttendance(){if(!erpAllowed('attendance'))return;showModal('Mark Class Attendance','Select a course to load allocated learners.',`<label>Course<select id="bulkCourse"><option value="">Select course</option>${erpItems('courses').map(c=>`<option value="${escHtml(c.id||c.code)}">${escHtml(c.title)}</option>`).join('')}</select></label><label>Date<input id="bulkDate" type="date" value="${erpDate()}"></label><div id="bulkLearners"></div>`,()=>{const states={};$$('[data-bulk-student]').forEach(el=>states[el.dataset.bulkStudent]=el.value);if(!Object.keys(states).length)return alert('No allocated learners for this course.');try{erpMarkClass($('#bulkCourse').value,$('#bulkDate').value,states);closeModal();renderErpModule('attendance')}catch(err){alert(err.message)}});$('#bulkCourse').onchange=()=>{$('#bulkLearners').innerHTML=erpItems('students').filter(s=>erpItems('enrolments').some(e=>e.studentId===s.id&&e.courseId===$('#bulkCourse').value&&e.status==='active')).map(s=>`<label>${escHtml(s.name)}<select data-bulk-student="${s.id}"><option>Present</option><option>Absent</option><option>Late</option><option>Excused</option></select></label>`).join('')||'<p>No allocated learners found.</p>'}}
const erpV2RenderModule=renderErpModule;
renderErpModule=function(key){erpV2RenderModule(key);if(key==='attendance'&&erpAllowed(key)){const b=document.createElement('button');b.className='primary-btn';b.textContent='Mark Whole Class';b.onclick=erpBulkAttendance;$('#content .toolbar').append(b)}};
function renderErpRecovery(){if(!['admin','super_admin'].includes(currentUser.role))return;$('#content').innerHTML=pageHead('Recycle Bin','Deleted records remain recoverable in this browser.')+`<section class="card">${erpItems('trash').map(t=>`<div class="recovery-row"><div><strong>${escHtml(ERP_MODULES[t.module]?.title||t.module)}</strong><p>${escHtml(t.record.name||t.record.title||t.record.reference||t.record.id)} · ${escHtml(t.removedAt)}</p></div><button class="secondary-btn" data-restore-record="${t.id}">Restore</button></div>`).join('')||'<p>No deleted records.</p>'}</section>`;$$('[data-restore-record]').forEach(b=>b.onclick=()=>{try{erpRestoreRecord(b.dataset.restoreRecord);renderErpRecovery()}catch(err){alert(err.message)}})}
const erpV2Navigate=navigate;
navigate=function(page){if(page==='recovery'){currentPage=page;$('#pageTitle').textContent='Recycle Bin';$$('#sideNav .nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));renderErpRecovery();return;}erpV2Navigate(page);$('#sidebar').classList.remove('open')};
adminNav.push(['recovery','↺','Recycle Bin']);navByRole.admin=adminNav;navByRole.super_admin=[...adminNav];
renderDashboard=function(){if(!['admin','super_admin'].includes(currentUser.role)){renderDashboardLegacy();return;}const invoices=erpItems('invoices'),due=invoices.filter(i=>i.date<erpDate()&&erpInvoiceBalance(i)>0),outstanding=invoices.reduce((s,i)=>s+erpInvoiceBalance(i),0),verified=erpItems('payments').filter(p=>p.status==='Verified').reduce((s,p)=>s+Number(p.amount),0);$('#content').innerHTML=`<section class="command-hero"><div><span class="eyebrow">ETHAN DIGITAL ACADEMY ERP · WORKSPACE</span><h1>Academy Overview</h1><p>Manage admissions, learners, classes and academy finance.</p></div><button class="primary-btn" onclick="navigate('admissions')">Open Admissions</button></section><div class="stats-grid">${stat('Active learners',erpItems('students').filter(s=>s.status==='Active').length,'Registered learner records','▤')}${stat('Verified receipts',ethanMoney(verified),'Workspace receipts','₦')}${stat('Outstanding',ethanMoney(outstanding),due.length+' overdue invoices','₦')}${stat('New applications',erpItems('admissions').filter(a=>['New','Under review'].includes(a.status)).length,'Awaiting review','▤')}</div><div class="dashboard-grid"><section class="card"><h3>Today’s Classes</h3>${erpItems('timetable').filter(t=>t.date===erpDate()).sort((a,b)=>a.start.localeCompare(b.start)).map(t=>`<p><strong>${escHtml(erpLookup('courses',t.courseId))}</strong><br>${escHtml(t.start)}–${escHtml(t.end)} · ${escHtml(t.location)}</p>`).join('')||'<p>No classes scheduled for today.</p>'}</section><section class="card"><h3>Finance Follow-up</h3>${due.slice(0,6).map(i=>`<p>${escHtml(erpLookup('students',i.studentId))} · ${ethanMoney(erpInvoiceBalance(i))} · Due ${escHtml(i.date)}</p>`).join('')||'<p>No overdue invoices.</p>'}<button class="secondary-btn" onclick="navigate('invoices')">View Invoices</button></section></div><section class="card"><h3>Quick Actions</h3><div class="quick-grid">${[['Learners','students'],['Courses','courses'],['Payments','payments'],['Attendance','attendance'],['Reports','reports'],['Backup & Equipment','operations']].map(([label,key])=>`<button class="secondary-btn" onclick="navigate('${key}')">${label}</button>`).join('')}</div></section>`};
// Legacy receipts are deliberately not assigned to invoices automatically.
window.addEventListener('DOMContentLoaded',()=>{if(currentUser){renderNav();navigate('dashboard')}});

const erpV2Reports=renderReports;
renderReports=function(){erpV2Reports();const unassigned=erpItems('payments').filter(p=>p.status==='Verified'&&!p.invoiceId).reduce((s,p)=>s+Number(p.amount),0);const section=document.createElement('section');section.className='card';section.innerHTML=`<h3>Invoice Reconciliation</h3><p>Outstanding invoices: <strong>${ethanMoney(erpItems('invoices').reduce((s,i)=>s+erpInvoiceBalance(i),0))}</strong></p><p>Verified receipts awaiting invoice assignment: <strong>${ethanMoney(unassigned)}</strong></p><p class="muted">Unassigned receipts are included in cash totals, but do not reduce any invoice balance. Edit the receipt to select its invoice.</p>`;$('#content').append(section)};
ERP_MODULES.enrolments={title:'Course Allocations',note:'Review allocated course access and mark an allocation active, paused, completed or cancelled.',fields:[['studentId','Learner','students'],['courseId','Course','courses'],['status','Status',['active','paused','completed','cancelled']]]};
adminNav.push(['enrolments','▤','Course Allocations']);navByRole.admin=adminNav;navByRole.super_admin=[...adminNav];
const erpV3Validate=erpValidateRow;
erpValidateRow=function(key,row){erpV3Validate(key,row);if(key==='enrolments'&&erpItems(key).some(r=>r.id!==row.id&&r.studentId===row.studentId&&r.courseId===row.courseId))throw Error('A course allocation already exists. Edit its status instead.');};
studentEnrolments=function(){if(currentUser?.role!=='student')return [];if(window.ETHAN_BACKEND?.ready)return (portalState.myEnrolments||[]).filter(e=>['active','completed'].includes(e.status||'active'));const learner=erpItems('students').find(s=>String(s.email||'').toLowerCase()===String(currentUser.email||'').toLowerCase());if(!learner)return [];return erpItems('enrolments').filter(e=>e.studentId===learner.id&&['active','completed'].includes(e.status||'active')).map(e=>({...e,course:erpItems('courses').find(c=>(c.id||c.code)===e.courseId||c.code===e.courseCode)})).filter(e=>e.course)};
