import * as T from './three.module.js';
import { GLTFLoader } from './GLTFLoader.js';
import { clone as cloneSkeleton } from './SkeletonUtils.js';
import { mergeGeometries } from './BufferGeometryUtils.js';
const $=id=>document.getElementById(id),rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});}catch(e){$('error').hidden=false;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer:coarse)').matches?1.25:1.6));renderer.shadowMap.enabled=!matchMedia('(pointer:coarse)').matches;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color('#91d9ec');scene.fog=new T.Fog('#a9dfe4',65,190);
const camera=new T.PerspectiveCamera(65,innerWidth/innerHeight,.1,350);const sun=new T.DirectionalLight('#fff5d6',2.5);sun.position.set(50,90,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-85,right:85,top:85,bottom:-85,far:200});sun.shadow.bias=-.001;scene.add(sun,new T.HemisphereLight('#d9f5ff','#538251',2));
const materials=new Map();function mat(c){if(!materials.has(c))materials.set(c,new T.MeshStandardMaterial({color:c,roughness:.9}));return materials.get(c);}
const boxGeo=new T.BoxGeometry(1,1,1),sphereGeo=new T.SphereGeometry(1,10,8);boxGeo.userData.shared=true;sphereGeo.userData.shared=true;function box(parent,x,y,z,w,h,d,color){let m=new T.Mesh(boxGeo,mat(color));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function sphere(parent,x,y,z,r,color){let m=new T.Mesh(sphereGeo,mat(color));m.position.set(x,y,z);m.scale.setScalar(r);m.castShadow=true;parent.add(m);return m;}
const obstacles=[],structures=[];let cityGroup=new T.Group();scene.add(cityGroup);
const worldThemes=[{name:'Central City',sky:'#afcad8',fog:'#bfd0d8',wall:['#a9adb1','#c8beb1','#afb5b6'],floors:4},{name:'Old Town',sky:'#d6d4ca',fog:'#d9d6c9',wall:['#b69582','#c6b896','#aaae96'],floors:2},{name:'Industrial District',sky:'#b8c3c7',fog:'#c4cbcc',wall:['#839099','#a0988d','#8c9695'],floors:3},{name:'Night City',sky:'#182b43',fog:'#22384e',wall:['#505d75','#5d677c','#635b6d'],floors:5},{name:'Riverside District',sky:'#9cced8',fog:'#b4d8dd',wall:['#b3c2c2','#d0c3ad','#9db3bb'],floors:3},{name:'Garden Quarter',sky:'#b6d9df',fog:'#c7dce0',wall:['#e0d0b3','#b7bc9e','#beaa93'],floors:2},{name:'Winter City',sky:'#c8d4df',fog:'#d8e2e8',wall:['#9caebb','#bec6c9','#afb8bc'],floors:4},{name:'Sunset Skyline',sky:'#d8a382',fog:'#d5b39a',wall:['#a29b95','#a8a4b1','#b6aaa0'],floors:6}];
function buildCity(index=0){cityGroup.traverse(n=>{if(n.isMesh&&!n.geometry.userData.shared)n.geometry.dispose();});scene.remove(cityGroup);cityGroup=new T.Group();scene.add(cityGroup);obstacles.length=0;structures.length=0;const theme=worldThemes[index];scene.background.set(theme.sky);scene.fog.color.set(theme.fog);sun.intensity=index===3?1.3:2.3;box(cityGroup,0,-.2,0,250,.4,250,index===6?'#d9e0df':'#68756f');
 for(let c=-96;c<=96;c+=32){box(cityGroup,c,.015,0,10,.03,224,'#3c454b');box(cityGroup,0,.018,c,224,.03,10,'#3c454b');box(cityGroup,c-6,.06,0,2,.12,224,'#b7b5ad');box(cityGroup,c+6,.06,0,2,.12,224,'#b7b5ad');box(cityGroup,0,.065,c-6,224,.13,2,'#b7b5ad');box(cityGroup,0,.065,c+6,224,.13,2,'#b7b5ad');for(let q=-105;q<106;q+=9){box(cityGroup,c,.04,q,.15,.03,3,'#e0d5b1');box(cityGroup,q,.045,c,3,.03,.15,'#e0d5b1');}}
 for(let ix=-3;ix<3;ix++)for(let iz=-3;iz<3;iz++){const x=ix*32+16,z=iz*32+16,n=(ix+3)*6+iz+3;if(Math.hypot(x,z)>103)continue;if((n+index)%(index===5?3:7)===0){box(cityGroup,x,.1,z,17,.2,17,'#708866');for(let t=-1;t<=1;t+=2){box(cityGroup,x+t*5,1.3,z,.35,2.6,.35,'#6e5745');sphere(cityGroup,x+t*5,3,z,1.6,'#497355');}box(cityGroup,x,1,z+3,3,.3,.8,'#6c655a');continue;}
 const floors=theme.floors+((n+index)%2),h=floors*3,w=index===2?18:index===7?10:12,d=index===2?17:index===7?10:13;box(cityGroup,x,h/2,z,w,h,d,theme.wall[n%3]);box(cityGroup,x,h+.15,z,w+.5,.3,d+.5,index===6?'#e9f0ef':'#5d6970');box(cityGroup,x,.18,z,w+1,.36,d+1,'#999d9b');box(cityGroup,x,1.2,z+d/2+.03,1.7,2.4,.08,'#36434b');for(let floor=0;floor<floors;floor++){const y=floor*3+1.8,color=index===3?(floor%2?'#e1bf78':'#93cbdc'):'#668593';for(let q=-1;q<=1;q++){box(cityGroup,x+q*3.2,y,z+d/2+.06,1.5,1.5,.08,color);box(cityGroup,x+w/2+.06,y,z+q*3.2,.08,1.5,1.5,color);}}
 obstacles.push({x,z,w:w/2+.3,d:d/2+.3,h});structures.push({x,z,w,d});if(index===2){box(cityGroup,x-w*.3,h+.8,z,2,1.6,2,'#65717b');}
 }
 for(let i=0;i<14;i++){let x=(i%4-2)*32+4,z=(Math.floor(i/4)-1)*32+10;box(cityGroup,x,.55,z,1.7,.8,3.8,['#677d89','#934c42','#b7b6ae'][i%3]);box(cityGroup,x,1.1,z+.2,1.55,.6,2,'#677c88');for(let sign of [-1,1])for(let front of [-1,1])sphere(cityGroup,x+sign*.85,.4,z+front*1.2,.3,'#262a30');obstacles.push({x,z,w:1.1,d:2.2,h:1.4});}
 for(let i=-80;i<=80;i+=32){box(cityGroup,7,2.8,i,.15,5.6,.15,'#46515c');box(cityGroup,7,5.6,i,1.6,.2,.5,index===3?'#fff0ba':'#d2d4cc');}
batchCity();}
function batchCity(){cityGroup.updateMatrixWorld(true);let batches=new Map();cityGroup.traverse(n=>{if(n.isMesh){const list=batches.get(n.material)||[];list.push(n.geometry.clone().applyMatrix4(n.matrixWorld));batches.set(n.material,list);}});cityGroup.clear();for(let [material,geometries] of batches){let mesh=new T.Mesh(mergeGeometries(geometries,false),material);mesh.castShadow=true;mesh.receiveShadow=true;cityGroup.add(mesh);geometries.forEach(g=>g.dispose());}}
buildCity(0);
const zoneMesh=new T.Mesh(new T.CylinderGeometry(1,1,22,96,1,true),new T.MeshBasicMaterial({color:'#54c4ff',transparent:true,opacity:.13,side:T.DoubleSide,depthWrite:false}));zoneMesh.position.y=10;scene.add(zoneMesh);let linePoints=[];for(let i=0;i<=128;i++){let a=i/128*Math.PI*2;linePoints.push(new T.Vector3(Math.cos(a),.08,Math.sin(a)));}const zoneLine=new T.Line(new T.BufferGeometry().setFromPoints(linePoints),new T.LineBasicMaterial({color:'#affaff'}));scene.add(zoneLine);
// Textured, independently skinned humanoids with skeletal locomotion.
$('start').disabled=true;$('start').textContent='LOADING CHARACTER…';
let soldierAsset;
try{soldierAsset=await new GLTFLoader().loadAsync('./soldier.glb');}
catch(error){$('error').querySelector?.('h2')?.replaceChildren('Character could not load');$('errorMessage').textContent='The character download did not finish. Reconnect and tap Retry game.';$('error').hidden=false;throw error;}

const soldierBounds=new T.Box3().setFromObject(soldierAsset.scene),soldierHeight=soldierBounds.max.y-soldierBounds.min.y;
let visorNode;soldierAsset.scene.traverse(n=>{if(n.isMesh&&n.name.toLowerCase().includes('visor'))visorNode=n;});
const visorCentre=visorNode?new T.Box3().setFromObject(visorNode).getCenter(new T.Vector3()):new T.Vector3(0,0,-1);
const MODEL_FORWARD=visorCentre.z>0?Math.PI:0;
function outfitAvatar(g,color){g.userData.tintMaterials.forEach(m=>{m.color.copy(m.userData.baseColor).lerp(new T.Color(color),.22);});}
function avatar(color){
 let g=new T.Group(),model=cloneSkeleton(soldierAsset.scene);
 model.scale.setScalar(2.05/soldierHeight);model.position.y=-soldierBounds.min.y*model.scale.y;model.rotation.y=MODEL_FORWARD;g.add(model);
 const tintMaterials=[];model.traverse(node=>{if(node.isMesh){node.castShadow=true;node.receiveShadow=true;node.frustumCulled=false;const list=Array.isArray(node.material)?node.material:[node.material];const owned=list.map(original=>{let m=original.clone();m.userData.baseColor=m.color.clone();if(!original.name.toLowerCase().includes('visor'))tintMaterials.push(m);return m;});node.material=Array.isArray(node.material)?owned:owned[0];}});
 const mixer=new T.AnimationMixer(model),actions={};for(let clip of soldierAsset.animations){if(['Idle','Walk','Run'].includes(clip.name))actions[clip.name]=mixer.clipAction(clip);}
 actions.Idle.play();
 // A carried rifle, sized to the character rather than the old block avatar.
 const gun=new T.Group();box(gun,0,0,0,.12,.14,.65,'#283039');box(gun,0,.09,-.09,.07,.08,.15,'#5f7276');box(gun,0,-.13,.02,.075,.2,.09,'#243039');box(gun,0,0,-.44,.06,.06,.25,'#506369');box(gun,0,0,.37,.13,.16,.21,'#5b4c3d');gun.position.set(.35,1.2,-.38);gun.rotation.x=-.2;g.add(gun);
 g.userData={model,mixer,actions,currentAction:'Idle',tintMaterials,gun};outfitAvatar(g,color);scene.add(g);return g;
}
const player={x:0,z:38,y:0,vy:0,hp:100,armour:50,kills:0,kits:2,group:avatar('#b9f55a')};let bots=[],loot=[],effects=[],keys={},yaw=0,pitch=0,state='lobby',time=0,zoneR=104,phase=0,shotTimer=0,reloading=0,noticeTimer=0,gunIndex=0,muted=false,audio=null,walk=0,touchMove={x:0,y:0},heldFire=false;
function readProgress(){for(const key of ['ethanArenaProgress','ethanArenaProgressBackup']){try{const value=JSON.parse(localStorage.getItem(key)||'null');if(value&&typeof value==='object')return value;}catch{}}return null;}
let progression={coins:500,health:0,power:0,speed:0,armour:0,reload:0,capacity:0,xp:0,matches:0,wins:0};try{const saved=readProgress();if(saved&&typeof saved==='object')for(const k of Object.keys(progression)){if(Number.isFinite(saved[k])&&saved[k]>=0)progression[k]=Math.floor(Math.min(saved[k],['coins','xp'].includes(k)?1000000:10000));}}catch{}
for(const k of ['health','power','speed','armour','reload','capacity'])progression[k]=Math.min(5,Math.floor(progression[k]));
let gameMode='battle',activeDifficulty='normal',shotsFired=0,hitsLanded=0,crouched=false,grenadeCount=3,grenadeCooldown=0,settingsReturn='lobby';
let preferences={quality:matchMedia('(pointer:coarse)').matches?'low':'balanced',mouse:1,touch:1,assist:true,sound:true};try{const stored=JSON.parse(localStorage.getItem('ethanArenaSettings')||'null');if(stored){if(['low','balanced','high'].includes(stored.quality))preferences.quality=stored.quality;for(let key of ['mouse','touch'])if(Number.isFinite(stored[key]))preferences[key]=clamp(stored[key],.4,2);for(let key of ['assist','sound'])if(typeof stored[key]==='boolean')preferences[key]=stored[key];}}catch{}
let activeUpgrades={...progression};let worldIndex=0,mission='hunter',missionComplete=false,supplies=0,stamina=100,sprintExhausted=false,touchSprint=false,aiming=false,frontView=false,gyroEnabled=false,gyroLast=null,shopReturn='lobby',matchCoins=0;
function saveProgress(){try{const value=JSON.stringify(progression);localStorage.setItem('ethanArenaProgressBackup',value);localStorage.setItem('ethanArenaProgress',value);}catch{if($('shopMessage'))$('shopMessage').textContent='Device storage unavailable. Progress lasts for this session only.';}$('wallet').textContent=progression.coins;updateCareer();}
const upgrades={health:{title:'Vitality',detail:'+10 maximum health per level',cost:200},power:{title:'Weapon power',detail:'+8% weapon damage per level',cost:250},speed:{title:'Sprint training',detail:'+4% running speed per level',cost:180},armour:{title:'Starting armour',detail:'+10 armour per level',cost:200},reload:{title:'Reload training',detail:'8% faster reload per level',cost:220},capacity:{title:'Extended magazines',detail:'More ammunition per magazine',cost:240}};
function renderShop(){ $('shopCoins').textContent=progression.coins;$('shopItems').replaceChildren();for(const [key,item] of Object.entries(upgrades)){let level=progression[key],cost=item.cost*(level+1),row=document.createElement('div');row.className='shopItem';let text=document.createElement('div');text.textContent=item.title+' · level '+level+'/5';let info=document.createElement('span');info.textContent=item.detail;text.append(info);let button=document.createElement('button');button.textContent=level>=5?'MAX LEVEL':cost+' coins';button.disabled=level>=5||progression.coins<cost;button.onclick=()=>buyUpgrade(key);row.append(text,button);$('shopItems').append(row);}}
function buyUpgrade(key){if(!upgrades[key])return false;let level=progression[key],cost=upgrades[key].cost*(level+1);if(level>=5||progression.coins<cost){$('shopMessage').textContent='Not enough coins, or this upgrade is already at maximum.';return false;}progression.coins-=cost;progression[key]++;saveProgress();renderShop();$('shopMessage').textContent='Upgrade purchased. Applies at the start of your next match.';return true;}
function openShop(){shopReturn=state;if(state==='playing'){pause();shopReturn='paused';}state='shop';$('shop').hidden=false;renderShop();$('shopMessage').textContent='Earn coins from missions and matches. No real money purchases.';}
function closeShop(){state=shopReturn;$('shop').hidden=true;}
function award(coins){progression.coins=Math.min(1000000,progression.coins+Math.max(0,Math.floor(coins)));matchCoins+=coins;saveProgress();}
function maxHealth(){return 100+activeUpgrades.health*10;}
function updateCareer(){const level=1+Math.floor(progression.xp/250);$('career').textContent='LEVEL '+level+' · '+progression.coins+' COINS';let detail=document.createElement('span');detail.textContent=progression.wins+' wins / '+progression.matches+' matches · '+(250-progression.xp%250)+' XP to next level';$('career').append(detail);}
function earnXP(amount){if(gameMode==='training')return;progression.xp=Math.min(1000000,progression.xp+Math.max(0,Math.floor(amount)));saveProgress();}
function updateMission(){if(gameMode==='training'){$('missionHud').textContent='TRAINING · '+hitsLanded+' hits · '+(shotsFired?Math.round(hitsLanded/shotsFired*100):0)+'% accuracy';return;}let goals={hunter:3,supply:5,survive:90,champion:1,veteran:6,collector:10,endurance:180,accuracy:12},values={hunter:player.kills,supply:supplies,survive:Math.floor(time),champion:state==='ended'&&player.hp>0?1:0,veteran:player.kills,collector:supplies,endurance:Math.floor(time),accuracy:hitsLanded},names={hunter:'Eliminate 3 opponents',supply:'Collect 5 supplies',survive:'Survive 90 seconds',champion:'Win this match',veteran:'Eliminate 6 opponents',collector:'Collect 10 supplies',endurance:'Survive 180 seconds',accuracy:'Land 12 hits'},value=values[mission]||0;if(value>=goals[mission]&&!missionComplete){missionComplete=true;award(300);earnXP(150);notice('Mission complete · +300 coins · +150 XP');}$('missionHud').textContent=(missionComplete?'✓ COMPLETE · ':'MISSION · ')+names[mission]+' · '+Math.min(value,goals[mission])+'/'+goals[mission];}
const guns=[{name:'RANGER · RIFLE',mag:30,ammo:30,reserve:150,damage:25,rate:.16,range:75,reload:1.8},{name:'SWIFT · SMG',mag:40,ammo:40,reserve:160,damage:16,rate:.09,range:42,reload:1.5},{name:'THUNDER · SHOTGUN',mag:6,ammo:6,reserve:36,damage:66,rate:.8,range:23,reload:2.1},{name:'EAGLE · MARKSMAN',mag:12,ammo:12,reserve:60,damage:42,rate:.45,range:100,reload:2.3}];guns.forEach(g=>g.baseMag=g.mag);
function tone(freq,dur=.07,type='square',vol=.035){if(muted||!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.35),audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur);}
function notice(t){$('notice').textContent=t;$('notice').style.opacity=1;noticeTimer=3;}
function clearMatch(){clearFlames();clearGrenades();clearProjectiles();effects.forEach(e=>{e.mesh.geometry.dispose();e.mesh.material.dispose();});bots.forEach(b=>{scene.remove(b.group);b.group.userData.model.traverse(n=>{if(n.isSkinnedMesh)n.skeleton.dispose();if(n.isMesh){for(let m of (Array.isArray(n.material)?n.material:[n.material]))m.dispose();}});});loot.forEach(l=>scene.remove(l.group));effects.forEach(e=>scene.remove(e.mesh));bots=[];loot=[];effects=[];}
function free(x,z,r=.6){return Math.hypot(x,z)<105&&!obstacles.some(o=>Math.abs(x-o.x)<o.w+r&&Math.abs(z-o.z)<o.d+r);}
function spawnPoint(radius=85){for(let i=0;i<1000;i++){let x=rand(-radius,radius),z=rand(-radius,radius);if(Math.hypot(x,z)<radius&&free(x,z,2)&&Math.hypot(x-player.x,z-player.z)>15)return{x,z};}return{x:0,z:-40};}
function makeLoot(x,z,type){let g=new T.Group();g.position.set(x,.6,z);let color={health:'#f47875',ammo:'#efc957',armour:'#62c8ee'}[type];box(g,0,0,0,.65,.65,.65,color);if(type==='health'){box(g,0,.34,0,.45,.03,.13,'#fff4e7');box(g,0,.34,0,.13,.03,.45,'#fff4e7');}scene.add(g);loot.push({x,z,type,group:g});}
function start(){if(!['lobby','ended'].includes(state))return;clearMatch();gameMode=$('modeSelect').value==='training'?'training':'battle';activeDifficulty=$('difficulty').value;shotsFired=0;hitsLanded=0;crouched=false;grenadeCount=3;grenadeCooldown=0;zoneMesh.visible=zoneLine.visible=gameMode==='battle';activeUpgrades={...progression};worldIndex=clamp(Number($('worldSelect').value)||0,0,7);buildCity(worldIndex);mission=['hunter','supply','survive','champion','veteran','collector','endurance','accuracy'].includes($('missionSelect').value)?$('missionSelect').value:'hunter';missionComplete=false;supplies=0;stamina=100;sprintExhausted=false;matchCoins=0;heldFire=false;keys={};touchMove={x:0,y:0};aimPointer=null;stickEnd();frontView=false;$('cameraMode').textContent='V · Front view';aiming=false;gyroLast=null;touchSprint=false;$('sprint').textContent='SPRINT';$('aim').textContent='AIM';Object.assign(player,{x:0,z:38,y:0,vy:0,hp:maxHealth(),armour:50+activeUpgrades.armour*10,kills:0,kits:2});const colors={lime:'#b9f55a',blue:'#50c5ee',orange:'#ffa85c'};outfitAvatar(player.group,colors[$('outfit').value]);guns.forEach((g,i)=>{g.mag=g.baseMag+activeUpgrades.capacity*(i===2?1:i===3?2:5);g.ammo=g.mag;g.reserve=g.mag*5;});gunIndex=0;time=0;zoneR=104;phase=0;shotTimer=0;reloading=0;pitch=-.08;yaw=0;walk=0;for(let i=0;i<(gameMode==='training'?5:15);i++){let p=gameMode==='training'?{x:(i-2)*2,z:25-i*2}:spawnPoint();if(!free(p.x,p.z,1))p={x:0,z:25-i*3};bots.push({...p,hp:100,group:avatar(i%2?'#ef886f':'#cba3f6'),cool:rand(.5,3),angle:rand(0,6.28),age:0,alive:true});}for(let i=0;i<45;i++){let p=spawnPoint(96);makeLoot(p.x,p.z,['health','ammo','armour'][i%3]);}makeLoot(3,34,'ammo');makeLoot(-3,31,'armour');state='playing';$('menu').hidden=true;$('result').hidden=true;$('pauseMenu').hidden=true;$('hud').hidden=false;document.querySelector('.brand').style.display='none';try{const AudioEngine=window.AudioContext||window.webkitAudioContext;if(AudioEngine){audio??=new AudioEngine();audio.resume().catch(()=>{});}}catch{notice('Sound unavailable · you can still play');}notice(worldThemes[worldIndex].name+(gameMode==='training'?' · 5 targets · unlimited practice':' · 15 opponents · mission active'));updateMission();if(!matchMedia('(pointer:coarse)').matches)requestAimLock();updateHUD();}
function move(entity,dx,dz){if(free(entity.x+dx,entity.z))entity.x+=dx;if(free(entity.x,entity.z+dz))entity.z+=dz;}
function rayBox(origin,direction,min,max,limit){let lo=0,hi=limit;for(let axis of ['x','y','z']){if(Math.abs(direction[axis])<1e-8){if(origin[axis]<min[axis]||origin[axis]>max[axis])return null;continue;}let a=(min[axis]-origin[axis])/direction[axis],b=(max[axis]-origin[axis])/direction[axis];if(a>b)[a,b]=[b,a];lo=Math.max(lo,a);hi=Math.min(hi,b);if(lo>hi)return null;}return lo;}
function wallDistance(origin,direction,limit){let nearest=limit;for(let o of obstacles){let hit=rayBox(origin,direction,{x:o.x-o.w,y:0,z:o.z-o.d},{x:o.x+o.w,y:o.h,z:o.z+o.d},nearest);if(hit!==null)nearest=hit;}return nearest;}
function entityDistance(origin,direction,entity,limit){return rayBox(origin,direction,{x:entity.x-.4,y:(entity.y||0)+.08,z:entity.z-.4},{x:entity.x+.4,y:(entity.y||0)+(entity===player&&crouched?1.5:2.1),z:entity.z+.4},limit);}
function lineClear(a,b){const origin=new T.Vector3(a.x,1.45+(a.y||0),a.z),delta=new T.Vector3(b.x-origin.x,1.45+(b.y||0)-origin.y,b.z-origin.z),length=delta.length();return wallDistance(origin,delta.normalize(),length)>=length-.05;}
function hurt(entity,amount){if(entity===player){if(gameMode==='training')return;let absorb=Math.min(player.armour,amount*.6);player.armour-=absorb;player.hp-=amount-absorb;if(player.hp<=0)finish(false);}else{entity.hp-=amount;if(gameMode==='training'&&entity.hp<=0){entity.hp=100;return;}if(entity.hp<=0&&entity.alive){entity.alive=false;scene.remove(entity.group);makeLoot(entity.x,entity.z,Math.random()<.5?'health':'ammo');}}}
function trace(a,b,color){let geo=new T.BufferGeometry().setFromPoints([a,b]),mesh=new T.Line(geo,new T.LineBasicMaterial({color,transparent:true,opacity:1}));scene.add(mesh);effects.push({mesh,life:.12,dispose:true});}
const projectileGeometry=new T.SphereGeometry(.115,6,5),projectileMaterial=new T.MeshBasicMaterial({color:'#ffcf4c'}),enemyProjectileMaterial=new T.MeshBasicMaterial({color:'#ff7553'});
const projectilePool=Array.from({length:96},()=>{let mesh=new T.Mesh(projectileGeometry,projectileMaterial);mesh.visible=false;mesh.renderOrder=4;scene.add(mesh);return{mesh,active:false,dir:new T.Vector3(),remaining:0,damage:0,owner:null};});
function clearProjectiles(){for(let p of projectilePool){p.active=false;p.mesh.visible=false;}}
function launchProjectile(origin,direction,owner,damage,range){let p=projectilePool.find(p=>!p.active);if(!p)return;p.active=true;p.mesh.visible=true;p.mesh.position.copy(origin);p.dir.copy(direction).normalize();p.owner=owner;p.damage=damage;p.remaining=range;p.mesh.material=owner===player?projectileMaterial:enemyProjectileMaterial;p.mesh.scale.setScalar(owner===player?1.3:1);}
function stepProjectiles(dt){for(let p of projectilePool){if(!p.active)continue;const travel=Math.min(p.remaining,85*dt),origin=p.mesh.position;let closest=wallDistance(origin,p.dir,travel),victim=null;for(let entity of [player,...bots]){if(entity===p.owner||entity===player&&player.hp<=0||entity!==player&&!entity.alive)continue;let hit=entityDistance(origin,p.dir,entity,closest);if(hit!==null&&hit<closest){closest=hit;victim=entity;}}
 if(victim||closest<travel-.0001){origin.addScaledVector(p.dir,closest);if(victim){const alive=victim===player?player.hp>0:victim.alive;hurt(victim,p.damage);if(p.owner===player){hitsLanded++;hitTimer=.16;$('crosshair').style.color='#ffdc70';$('damageFeedback').textContent=Math.ceil(p.damage)+' DAMAGE';damageTimer=.7;if(alive&&victim!==player&&!victim.alive){player.kills++;notice('Opponent eliminated');tone(600,.18,'sine');}}}p.active=false;p.mesh.visible=false;}
 else{origin.addScaledVector(p.dir,travel);p.remaining-=travel;if(p.remaining<=0){p.active=false;p.mesh.visible=false;}}
 }}
const ray=new T.Raycaster(),v=new T.Vector3();let hitTimer=0,damageTimer=0,weaponKick=0;
const viewGun=player.group.userData.gun.clone(true);viewGun.traverse(n=>{if(n.isMesh){n.material=n.material.clone();n.material.depthTest=false;n.material.depthWrite=false;n.renderOrder=1000;}});viewGun.position.set(.38,-.3,-.72);viewGun.rotation.set(0,-.1,0);camera.add(viewGun);scene.add(camera);
box(viewGun,-.07,-.13,.15,.12,.17,.24,'#bf926c');box(viewGun,-.07,-.22,.29,.17,.15,.22,'#283f49');viewGun.children.slice(-2).forEach(n=>{n.material=n.material.clone();n.material.depthTest=false;n.material.depthWrite=false;n.renderOrder=1001;});
function fire(){if(state!=='playing'||shotTimer>0||reloading)return;if(frontView){notice('Press V to return to the aiming view');return;}let g=guns[gunIndex];if(g.ammo<=0){if(gameMode==='training')g.reserve=Math.max(g.reserve,g.mag*5);reloadGun();return;}updateCamera(0);camera.updateMatrixWorld(true);ray.setFromCamera(new T.Vector2(0,0),camera);let cameraDirection=ray.ray.direction,limit=wallDistance(camera.position,cameraDirection,g.range+6),direct=null;for(let b of bots){if(!b.alive)continue;let hit=entityDistance(camera.position,cameraDirection,b,limit);if(hit!==null&&hit<limit){direct=b;limit=hit;}}
 let aimPoint=ray.ray.at(limit,new T.Vector3());if(!direct){let best=preferences.assist?(aiming?.05:.06):0;for(let b of bots){if(!b.alive||Math.hypot(b.x-player.x,b.z-player.z)>g.range)continue;v.set(b.x,1.35,b.z).sub(camera.position);const angle=v.angleTo(cameraDirection);if(angle<best&&lineClear(player,b)){best=angle;direct=b;aimPoint.set(b.x,1.35,b.z);}}}
 const origin=gunMuzzle(viewGun),direction=aimPoint.sub(origin).normalize();g.ammo--;shotTimer=g.rate;weaponKick=.09;tone(gunIndex===2?90:170,.09,'sawtooth',.045);
 const pellets=gunIndex===2?5:1;shotsFired+=pellets;for(let i=0;i<pellets;i++){let dir=direction.clone();if(pellets>1)dir.add(new T.Vector3(rand(-.035,.035),rand(-.028,.028),rand(-.035,.035))).normalize();launchProjectile(origin,dir,player,g.damage*(1+activeUpgrades.power*.08)/pellets,g.range);}
 muzzleFlash(player);updateHUD();}
function reloadGun(){let g=guns[gunIndex];if(state!=='playing'||reloading||g.ammo===g.mag||g.reserve<=0)return;reloading=g.reload*(1-activeUpgrades.reload*.08);notice('Reloading…');tone(330,.1,'triangle');}
function swapGun(index){if(state!=='playing')return;gunIndex=index??(gunIndex+1)%guns.length;gunIndex=clamp(gunIndex,0,guns.length-1);reloading=0;updateHUD();notice(guns[gunIndex].name);}
function heal(){if(state!=='playing')return;if(player.kits<=0){notice('No health kits · look for red supply boxes');return;}if(player.hp>=maxHealth()){notice('Health is already full');return;}player.kits--;player.hp=Math.min(maxHealth(),player.hp+45);notice('Health restored · '+player.kits+' kits remaining');tone(500,.25,'sine');updateHUD();}
function jump(){if(state==='playing'&&player.y<=.001)player.vy=7;}
function updateHUD(){let g=guns[gunIndex];$('matchDetails').textContent=worldThemes[worldIndex].name+' · '+Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0')+' · '+(shotsFired?Math.min(100,Math.round(hitsLanded/shotsFired*100)):0)+'% hits';$('grenade').textContent='GRENADE '+grenadeCount;$('crouch').textContent=crouched?'STAND · C':'CROUCH · C';$('staminaText').textContent='SPRINT '+Math.ceil(stamina)+'%';$('hpText').textContent=Math.ceil(Math.max(0,player.hp));$('hpBar').style.width=clamp(player.hp/maxHealth()*100,0,100)+'%';$('armourText').textContent='ARMOUR '+Math.ceil(player.armour)+' · KITS '+player.kits;$('gunName').textContent=g.name;$('ammo').textContent=g.ammo;$('reserve').textContent=' / '+g.reserve;$('kills').textContent=player.kills;$('alive').textContent=bots.filter(b=>b.alive).length+(player.hp>0?1:0);$('reloadState').textContent=reloading?'Reloading…':'R reload · 1 / 2 / 3 / 4 switch';let t=Math.max(0,Math.ceil(45-time));$('zoneTime').textContent=gameMode==='training'?'PRACTICE':time<45?'0:'+String(t).padStart(2,'0'):'SHRINKING';}
function finish(won){if(state!=='playing')return;state='ended';clearFlames();clearProjectiles();if(gameMode==='training'){lobby();return;}progression.matches++;if(won)progression.wins++;award((won?400:75)+player.kills*40);earnXP((won?300:75)+player.kills*25);updateMission();heldFire=false;keys={};document.exitPointerLock?.();$('result').hidden=false;$('resultTitle').textContent=won?'VICTORY!':'ELIMINATED';$('resultTag').textContent=won?'LAST SURVIVOR OF THE CITY':'EVERY MATCH IS A NEW CHANCE';let place=won?1:bots.filter(b=>b.alive).length+1;$('resultInfo').textContent='Placement #'+place+' · '+player.kills+' eliminations · '+Math.floor(time/60)+'m '+Math.floor(time%60)+'s survived · '+matchCoins+' coins earned · Level '+(1+Math.floor(progression.xp/250));tone(won?700:140,.5,'triangle');}
function pause(){if(state!=='playing')return;stickEnd();aimPointer=null;touchSprint=false;aiming=false;$('sprint').textContent='SPRINT';$('aim').textContent='AIM';state='paused';heldFire=false;keys={};touchMove={x:0,y:0};$('pauseMenu').hidden=false;document.exitPointerLock?.();}
function resume(){if(state!=='paused')return;state='playing';$('pauseMenu').hidden=true;if(!matchMedia('(pointer:coarse)').matches)requestAimLock();}
function lobby(){state='lobby';player.group.scale.y=1;frontView=false;aiming=false;touchSprint=false;touchMove={x:0,y:0};stickEnd();aimPointer=null;gyroLast=null;$('shop').hidden=true;$('settings').hidden=true;zoneMesh.visible=zoneLine.visible=true;saveProgress();clearMatch();$('menu').hidden=false;$('hud').hidden=true;$('pauseMenu').hidden=true;$('result').hidden=true;document.querySelector('.brand').style.display='';document.exitPointerLock?.();heldFire=false;keys={};player.group.visible=true;}
function animateAvatar(g,x,z,y,angle,moving,t,dt=.016,sprinting=false){
 g.position.set(x,y,z);g.rotation.y=angle;let d=g.userData,name=moving?(sprinting?'Run':'Walk'):'Idle';
 if(name!==d.currentAction){let previous=d.actions[d.currentAction],next=d.actions[name];next.reset().setEffectiveTimeScale(1).setEffectiveWeight(1).play();previous.crossFadeTo(next,.18,true);d.currentAction=name;}
 d.mixer.update(dt);d.gun.position.y=1.23+(moving?Math.sin(t*10)*.025:Math.sin(t*2)*.008);
 if(y>0){d.model.rotation.x=-.07;d.gun.rotation.x=-.3;}else{d.model.rotation.x=0;d.gun.rotation.x=-.2;}
}
const mapctx=$('map').getContext('2d');function drawMap(){let c=mapctx;c.clearRect(0,0,160,160);c.fillStyle='#284c43';c.beginPath();c.arc(80,80,75,0,7);c.fill();c.strokeStyle='#a6f6ff';c.lineWidth=2;c.beginPath();c.arc(80,80,zoneR*.68,0,7);c.stroke();c.fillStyle='#bea989';for(let o of structures)c.fillRect(80+o.x*.68-o.w*.34,80+o.z*.68-o.d*.34,o.w*.68,o.d*.68);c.fillStyle='#ffc56e';for(let b of bots)if(b.alive&&Math.hypot(b.x-player.x,b.z-player.z)<30){c.beginPath();c.arc(80+b.x*.68,80+b.z*.68,2,0,7);c.fill();}c.save();c.translate(80+player.x*.68,80+player.z*.68);c.rotate(-yaw);c.fillStyle='#b9f55a';c.beginPath();c.moveTo(0,-6);c.lineTo(-4,4);c.lineTo(4,4);c.closePath();c.fill();c.restore();}
function tick(dt){if(state!=='playing')return;time+=dt;stepGrenades(dt);stepProjectiles(dt);grenadeCooldown=Math.max(0,grenadeCooldown-dt);if(state!=='playing')return;shotTimer=Math.max(0,shotTimer-dt);if(reloading){reloading-=dt;if(reloading<=0){let g=guns[gunIndex],take=Math.min(g.mag-g.ammo,g.reserve);g.ammo+=take;g.reserve-=take;reloading=0;notice('Ready');}}if(gameMode==='battle'&&time>45){zoneR=Math.max(7,104-(time-45)*.35);let p=Math.floor((time-45)/60);if(p!==phase){phase=p;notice('Safe zone is shrinking · move toward the centre');}}zoneMesh.scale.set(zoneR,1,zoneR);zoneLine.scale.set(zoneR,1,zoneR);if(gameMode==='battle'&&Math.hypot(player.x,player.z)>zoneR){hurt(player,6*dt);if(state!=='playing')return;if(noticeTimer<=0)notice('Outside safe zone · head toward the centre!');}let f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)-touchMove.y,s=(keys.KeyD?1:0)-(keys.KeyA?1:0)+touchMove.x;if(keys.ArrowLeft)yaw+=dt*1.6;if(keys.ArrowRight)yaw-=dt*1.6;let n=Math.hypot(f,s),sprinting=(keys.ShiftLeft||keys.ShiftRight||touchSprint)&&!sprintExhausted&&stamina>1&&n>.1&&!crouched,speed=(crouched?3:sprinting?10:6)*(1+activeUpgrades.speed*.04);stamina=clamp(stamina+(sprinting?-22:15)*dt,0,100);if(stamina<=1)sprintExhausted=true;if(stamina>=25)sprintExhausted=false;if(n>1){f/=n;s/=n;}move(player,(Math.sin(yaw)*f+Math.cos(yaw)*s)*speed*dt,(-Math.cos(yaw)*f+Math.sin(yaw)*s)*speed*dt);player.vy-=18*dt;player.y=Math.max(0,player.y+player.vy*dt);if(player.y===0)player.vy=0;walk+=dt;player.group.visible=true;player.group.scale.y=crouched?.73:1;animateAvatar(player.group,player.x,player.z,player.y,(n>.1&&!heldFire&&!keys.KeyG&&!keys.KeyF&&!keys.KeyH&&!keys.KeyJ)?Math.atan2(-(Math.sin(yaw)*f+Math.cos(yaw)*s),-(-Math.cos(yaw)*f+Math.sin(yaw)*s)):-yaw,n>.1,walk,dt,sprinting);if(heldFire||keys.KeyG||keys.KeyF||keys.KeyH||keys.KeyJ)fire();
for(let b of bots){if(!b.alive)continue;if(gameMode==='training'){animateAvatar(b.group,b.x,b.z,0,Math.PI,false,time,dt);continue;}b.cool-=dt;b.age+=dt;if(Math.hypot(b.x,b.z)>zoneR)hurt(b,8*dt);if(!b.alive)continue;let dist=Math.hypot(player.x-b.x,player.z-b.z),target=player;for(let other of bots){if(other!==b&&other.alive){let d=Math.hypot(other.x-b.x,other.z-b.z);if(d<dist){dist=d;target=other;}}}let dx=target.x-b.x,dz=target.z-b.z,ang=Math.atan2(dx,dz);if(Math.hypot(b.x,b.z)>zoneR-5){dx=-b.x;dz=-b.z;dist=Math.hypot(dx,dz);}else if(dist<38&&lineClear(b,target)){if(b.cool<=0){b.cool=rand(.8,1.9)*(activeDifficulty==='hard'?.65:activeDifficulty==='easy'?1.5:1);aimBotGun(b,target);muzzleFlash(b);let accuracy=activeDifficulty==='hard'?.65:activeDifficulty==='easy'?.22:.4,origin=gunMuzzle(b.group.userData.gun),destination=new T.Vector3(target.x,1.2+(target.y||0),target.z);if(Math.random()>accuracy)destination.add(new T.Vector3(rand(-3,3),rand(-1,2),rand(-3,3)));launchProjectile(origin,destination.sub(origin).normalize(),b,rand(5,11),45);}if(dist<12){dx=0;dz=0;}}else if(b.age>2){b.age=0;b.angle+=rand(-1.5,1.5);}if(dist>38&&Math.hypot(b.x,b.z)<zoneR-5){dx=Math.sin(b.angle);dz=Math.cos(b.angle);}let len=Math.hypot(dx,dz)||1,oldx=b.x,oldz=b.z;let desired=Math.atan2(dx,dz);if(!free(b.x+dx/len*1.5,b.z+dz/len*1.5,.65)){for(let offset of [.7,-.7,1.4,-1.4,2.1,-2.1,Math.PI]){let alternate=desired+offset;if(free(b.x+Math.sin(alternate)*1.8,b.z+Math.cos(alternate)*1.8,.65)){dx=Math.sin(alternate);dz=Math.cos(alternate);len=1;break;}}}const botSpeed=activeDifficulty==='easy'?.65:activeDifficulty==='hard'?.95:.8;move(b,dx/len*botSpeed*dt,dz/len*botSpeed*dt);if(oldx===b.x&&oldz===b.z)b.angle+=dt*3;const movedX=b.x-oldx,movedZ=b.z-oldz,moving=Math.hypot(movedX,movedZ)>.0001,facing=moving?Math.atan2(-movedX,-movedZ):Math.atan2(-(target.x-b.x),-(target.z-b.z));animateAvatar(b.group,b.x,b.z,0,facing,moving,time+b.angle,dt*(botSpeed/1.6));aimBotGun(b,target);}
for(let i=loot.length-1;i>=0;i--){let l=loot[i];l.group.rotation.y+=dt;l.group.position.y=.65+Math.sin(time*2+i)*.12;if(Math.hypot(l.x-player.x,l.z-player.z)<1.8){supplies++;if(l.type==='health'){player.kits++;notice('Health kit collected · press E to heal');}else if(l.type==='armour'){player.armour=Math.min(100,player.armour+35);notice('Armour collected');}else{guns.forEach(g=>g.reserve+=g.mag);notice('Ammunition collected');}tone(660,.1,'sine');scene.remove(l.group);loot.splice(i,1);}}
if(gameMode==='battle'&&state==='playing'&&!bots.some(b=>b.alive))finish(true);uiElapsed+=dt;if(uiElapsed>=.1){uiElapsed=0;updateHUD();updateMission();drawMap();}}
function updateCamera(dt){viewGun.visible=['playing','paused'].includes(state)&&!frontView;if(state==='lobby'||state==='settings'&&settingsReturn==='lobby'||state==='shop'&&shopReturn==='lobby'){player.group.visible=true;player.group.scale.y=1;animateAvatar(player.group,0,0,0,Math.PI+.2,false,performance.now()/1000,dt);if(camera.fov!==65){camera.fov=65;camera.updateProjectionMatrix();}camera.position.set(.2,2.2,5.3);camera.lookAt(-1.3,1.15,0);zoneMesh.scale.set(104,1,104);zoneLine.scale.set(104,1,104);return;}
 const targetFov=aiming?48:65;if(camera.fov!==targetFov){camera.fov=targetFov;camera.updateProjectionMatrix();}const forward=new T.Vector3(Math.sin(yaw),0,-Math.cos(yaw)),right=new T.Vector3(Math.cos(yaw),0,Math.sin(yaw));if(frontView){camera.position.set(player.x+forward.x*5.5,player.y+2.4,player.z+forward.z*5.5);camera.lookAt(player.x,player.y+1.2,player.z);return;}
 const focus=new T.Vector3(player.x,player.y+(crouched?1.15:1.65),player.z).addScaledVector(right,.65),desired=focus.clone().addScaledVector(forward,aiming?-2.4:-3.2);desired.y+=aiming?.38:.65;let delta=desired.clone().sub(focus),distance=delta.length(),blocked=wallDistance(focus,delta.normalize(),distance);camera.position.copy(focus).addScaledVector(delta,Math.max(.4,blocked-.25));const aim=forward.clone();aim.y=pitch*.55;aim.normalize();camera.lookAt(camera.position.clone().addScaledVector(aim,20));viewGun.position.set(aiming?.18:.38,-.3-Math.sin(walk*9)*.005,-.72+weaponKick);viewGun.scale.setScalar(gunIndex===2?1.12:gunIndex===1?.9:1);viewGun.rotation.x=-weaponKick*.8+(reloading?-.25:0);
}
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);globalThis.visualViewport?.addEventListener('resize',resize);addEventListener('orientationchange',()=>{stickEnd();aimPointer=null;heldFire=false;gyroLast=null;setTimeout(resize,150);});resize();let prev=performance.now(),accumulator=0,uiElapsed=0,barElapsed=0;
renderer.setAnimationLoop(now=>{const dt=Math.min(Math.max((now-prev)/1000,0),.1);prev=now;if(state==='playing'){accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps++<6){tick(1/60);accumulator-=1/60;if(state!=='playing'){accumulator=0;break;}}}else accumulator=0;
 if(noticeTimer>0){noticeTimer-=dt;if(noticeTimer<=0)$('notice').style.opacity=0;}hitTimer=Math.max(0,hitTimer-dt);if(!hitTimer)$('crosshair').style.color='';damageTimer=Math.max(0,damageTimer-dt);$('damageFeedback').style.opacity=damageTimer>0?1:0;weaponKick=Math.max(0,weaponKick-dt*.9);updateFlames(state==='paused'||state==='settings'||state==='shop'?0:dt);
 for(let i=effects.length-1;i>=0;i--){let e=effects[i];e.life-=dt;if(e.life<=0){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1);}}
 updateCamera(dt);barElapsed+=dt;if(barElapsed>=.1){barElapsed=0;updateEnemyBars();}renderer.render(scene,camera);});
$('start').onclick=start;$('again').onclick=start;$('lobby').onclick=lobby;$('quit').onclick=lobby;$('pause').onclick=pause;$('resume').onclick=resume;$('sound').onclick=()=>{muted=!muted;preferences.sound=!muted;$('sound').textContent=muted?'Sound off':'Sound on';storeSettings();};
addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement||e.target instanceof HTMLInputElement||e.target instanceof HTMLButtonElement&&state!=='playing')return;if(!['playing','paused'].includes(state))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape')pause();if(e.code==='Space')jump();if(e.code==='KeyR')reloadGun();if(e.code==='KeyE')heal();if(e.code==='KeyV')toggleCamera();if(e.code==='KeyZ')throwGrenade();if(e.code==='KeyC')toggleCrouch();if(['KeyG','KeyF','KeyH','KeyJ'].includes(e.code))fire();if(['Digit1','Digit2','Digit3','Digit4'].includes(e.code))swapGun(Number(e.code.slice(-1))-1);});addEventListener('keyup',e=>{keys[e.code]=false;});addEventListener('blur',()=>{if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing'&&!matchMedia('(pointer:coarse)').matches)pause();});
$('world').addEventListener('mousedown',e=>{if(state==='playing'&&e.button===2){aiming=true;return;}if(state==='playing'&&e.button===0){if(!document.pointerLockElement&&!matchMedia('(pointer:coarse)').matches)requestAimLock();heldFire=true;fire();}});addEventListener('mouseup',e=>{if(e.button===0)heldFire=false;if(e.button===2)aiming=false;});$('world').addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(state==='playing'&&(document.pointerLockElement=== $('world')||e.buttons===1)){yaw-=e.movementX*.003*preferences.mouse*(aiming?.7:1);pitch=clamp(pitch-e.movementY*.004*preferences.mouse*(aiming?.7:1),-.6,.8);}});
let stickPointer=null,stickOrigin=null;const stick=$('stick'),knob=stick.querySelector('i');stick.addEventListener('pointerdown',e=>{stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);let r=stick.getBoundingClientRect();stickOrigin={x:r.left+r.width/2,y:r.top+r.height/2};stickMotion(e);});function stickMotion(e){if(e.pointerId!==stickPointer||state!=='playing')return;let dx=e.clientX-stickOrigin.x,dy=e.clientY-stickOrigin.y,len=Math.hypot(dx,dy),max=38;if(len>max){dx*=max/len;dy*=max/len;}touchMove={x:dx/max,y:dy/max};knob.style.transform='translate('+dx+'px,'+dy+'px)';}stick.addEventListener('pointermove',stickMotion);function stickEnd(){stickPointer=null;touchMove={x:0,y:0};knob.style.transform='';}stick.addEventListener('pointerup',stickEnd);stick.addEventListener('pointercancel',stickEnd);
let aimPointer=null,aimPos=null;$('world').addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||state!=='playing')return;aimPointer=e.pointerId;aimPos={x:e.clientX,y:e.clientY};$('world').setPointerCapture(e.pointerId);});$('world').addEventListener('pointermove',e=>{if(e.pointerId!==aimPointer||state!=='playing')return;yaw-=(e.clientX-aimPos.x)*.006*preferences.touch*(aiming?.7:1);pitch=clamp(pitch-(e.clientY-aimPos.y)*.006*preferences.touch*(aiming?.7:1),-.6,.8);aimPos={x:e.clientX,y:e.clientY};});$('world').addEventListener('pointerup',()=>aimPointer=null);$('world').addEventListener('pointercancel',()=>aimPointer=null);
$('fire').addEventListener('pointerdown',e=>{e.preventDefault();$('fire').setPointerCapture(e.pointerId);heldFire=true;fire();});for(let event of ['pointerup','pointercancel'])$('fire').addEventListener(event,()=>heldFire=false);$('jump').onclick=jump;$('reload').onclick=reloadGun;$('swap').onclick=()=>swapGun();$('heal').onclick=heal;$('sprint').onclick=()=>{if(state!=='playing')return;touchSprint=!touchSprint;$('sprint').textContent=touchSprint?'SPRINT ON':'SPRINT';};$('aim').onclick=()=>{if(state!=='playing')return;aiming=!aiming;$('aim').textContent=aiming?'AIM ON':'AIM';};
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_match_status',description:'Read current arena match status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,health:Math.ceil(player.hp),survivors:bots.filter(b=>b.alive).length+(player.hp>0?1:0),eliminations:player.kills,weapon:guns[gunIndex].name})});}catch{}}
player.group.visible=true;

// Pooled flame bursts attach to the actual barrel and follow its recoil.
const flameGeometry=new T.ConeGeometry(1,1,7,1,true);
const flamePool=Array.from({length:20},()=>{const group=new T.Group(),layers=[];for(const [color,radius,length,offset] of [['#ff6b13',.1,.45,.2],['#ffcc39',.064,.3,.14],['#fff5c7',.03,.18,.08]]){const material=new T.MeshBasicMaterial({color,transparent:true,opacity:.9,blending:T.AdditiveBlending,depthWrite:false,side:T.DoubleSide});const mesh=new T.Mesh(flameGeometry,material);mesh.rotation.x=-Math.PI/2;mesh.position.z=-offset;mesh.scale.set(radius,length,radius);mesh.renderOrder=1002;group.add(mesh);layers.push(mesh);}group.visible=false;return{group,layers,life:0,duration:.1};});
function gunMuzzle(gun){gun.updateWorldMatrix(true,false);return gun.localToWorld(new T.Vector3(0,0,-.565));}
function aimBotGun(bot,target){bot.group.position.set(bot.x,0,bot.z);const gun=bot.group.userData.gun;gun.rotation.y=Math.atan2(-(target.x-bot.x),-(target.z-bot.z))-bot.group.rotation.y;gun.rotation.x=0;}
function clearFlames(){for(const flame of flamePool){flame.life=0;flame.group.visible=false;flame.group.removeFromParent();}}
function muzzleFlash(entity){const flame=flamePool.find(f=>f.life<=0);if(!flame)return;const foreground=entity===player,gun=foreground?viewGun:entity.group.userData.gun;flame.duration=foreground?.13:.09;flame.life=flame.duration;flame.group.visible=true;flame.group.position.set(0,0,-.565);flame.group.rotation.z=rand(0,Math.PI*2);flame.group.scale.setScalar(foreground?(gunIndex===2?1.3:1):.85);for(const layer of flame.layers){layer.material.depthTest=!foreground;layer.material.opacity=.95;layer.renderOrder=foreground?1002:5;}gun.add(flame.group);}
function updateFlames(dt){for(const flame of flamePool){if(flame.life<=0)continue;flame.life-=dt;if(flame.life<=0){flame.group.visible=false;flame.group.removeFromParent();continue;}const fade=flame.life/flame.duration;for(const layer of flame.layers)layer.material.opacity=fade*.95;flame.group.scale.multiplyScalar(1+dt*1.8);}}

function toggleCamera(){if(!['playing','paused'].includes(state))return;frontView=!frontView;$('cameraMode').textContent=frontView?'V · Return to aim':'V · Front view';notice(frontView?'Front view · press V to return to aiming':'Over shoulder view');}
const barPool=[];for(let i=0;i<15;i++){let bar=document.createElement('div');bar.className='enemyBar';bar.hidden=true;let label=document.createElement('span'),meter=document.createElement('i');bar.append(label,meter);bar.userData={label,meter};$('enemyBars').append(bar);barPool.push(bar);}
function updateEnemyBars(){let best=null,bestAngle=.13;const aimDir=camera.getWorldDirection(new T.Vector3());for(let i=0;i<15;i++){let b=bots[i],bar=barPool[i];if(!b||!b.alive||!['playing','paused'].includes(state)){bar.hidden=true;continue;}const dist=Math.hypot(b.x-player.x,b.z-player.z),pos=new T.Vector3(b.x,2.5,b.z),direction=pos.clone().sub(camera.position).normalize(),angle=direction.angleTo(aimDir);pos.project(camera);const visible=dist<45&&pos.z>-1&&pos.z<1&&Math.abs(pos.x)<1&&Math.abs(pos.y)<1&&lineClear(player,b);bar.hidden=!visible;if(visible){bar.style.left=(pos.x*.5+.5)*innerWidth+'px';bar.style.top=(-pos.y*.5+.5)*innerHeight+'px';bar.userData.label.textContent=Math.max(0,Math.ceil(b.hp))+' HP';bar.userData.meter.style.width=clamp(b.hp,0,100)+'%';if(angle<bestAngle){best=b;bestAngle=angle;}}} $('targetHud').style.display=best?'block':'none';if(best)$('targetHud').textContent='OPPONENT · '+Math.max(0,Math.ceil(best.hp))+' / 100 HP';}
async function toggleGyro(){if(gyroEnabled){gyroEnabled=false;gyroLast=null;updateGyroLabel('Gyro disabled');return;}if(typeof DeviceOrientationEvent==='undefined'){updateGyroLabel('Gyro unavailable on this device · use mouse or swipe');return;}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const permission=await DeviceOrientationEvent.requestPermission();if(permission!=='granted'){updateGyroLabel('Sensor access denied · use swipe aiming');return;}}gyroEnabled=true;gyroLast=null;updateGyroLabel('Gyro enabled · hold phone steady to calibrate');setTimeout(()=>{if(gyroEnabled&&!gyroLast){gyroEnabled=false;updateGyroLabel('No motion sensor detected · use swipe aiming');}},3000);}catch{gyroEnabled=false;updateGyroLabel('Gyro unavailable · use mouse or swipe');}}
function updateGyroLabel(text){$('gyroStatus').textContent=text;$('gyroLobby').textContent=gyroEnabled?'DISABLE GYRO':'ENABLE GYRO';$('gyroHud').textContent=gyroEnabled?'Gyro on':'Gyro off';}
function gyroMotion(e){if(!gyroEnabled||!Number.isFinite(e.beta)||!Number.isFinite(e.gamma))return;const current={beta:e.beta,gamma:e.gamma};if(gyroLast&&state==='playing'&&!frontView){const sensitivity=Number($('gyroSensitivity').value)||.7;let dx=current.gamma-gyroLast.gamma,dy=current.beta-gyroLast.beta;if(Math.abs(dx)<30&&Math.abs(dy)<30){const angle=globalThis.screen?.orientation?.angle||0;const landscape=Math.abs(angle)===90;const horizontal=landscape?dy*Math.sign(angle):dx,vertical=landscape?-dx*Math.sign(angle):dy;yaw-=horizontal*.012*sensitivity;pitch=clamp(pitch-vertical*.009*sensitivity,-.6,.8);}}gyroLast=current;}
addEventListener('deviceorientation',gyroMotion);$('gyroLobby').onclick=toggleGyro;$('gyroHud').onclick=toggleGyro;$('cameraMode').onclick=toggleCamera;$('openShop').onclick=openShop;$('pauseShop').onclick=openShop;$('closeShop').onclick=closeShop;$('worldSelect').onchange=()=>{if(state==='lobby')buildCity(Number($('worldSelect').value)||0);};saveProgress();

function requestAimLock(){try{const pending=$('world').requestPointerLock?.();pending?.catch?.(()=>notice('Click the game to enable mouse aiming'));}catch{notice('Click the game to enable mouse aiming');}}

const grenadePool=Array.from({length:6},()=>{const mesh=new T.Mesh(new T.SphereGeometry(.18,7,5),mat('#7d9058'));mesh.visible=false;scene.add(mesh);return{mesh,active:false,velocity:new T.Vector3(),timer:0};});
function clearGrenades(){for(let grenade of grenadePool){grenade.active=false;grenade.mesh.visible=false;}}
function throwGrenade(){if(state!=='playing'||frontView||grenadeCooldown>0)return;if(grenadeCount<=0){notice('No grenades remaining');return;}const g=grenadePool.find(g=>!g.active);if(!g)return;g.active=true;g.mesh.visible=true;g.mesh.position.set(player.x,1.5+player.y,player.z);g.velocity.set(Math.sin(yaw)*12,5,-Math.cos(yaw)*12);g.timer=1.8;grenadeCount--;grenadeCooldown=3;notice('Grenade thrown');updateHUD();}
function stepGrenades(dt){for(let g of grenadePool){if(!g.active)continue;g.timer-=dt;g.velocity.y-=12*dt;const next=g.mesh.position.clone().addScaledVector(g.velocity,dt);if(free(next.x,next.z,.2)){g.mesh.position.copy(next);}else{g.velocity.x*=-.4;g.velocity.z*=-.4;g.mesh.position.y=next.y;}if(g.mesh.position.y<.2){g.mesh.position.y=.2;g.velocity.y=Math.abs(g.velocity.y)*.35;g.velocity.x*=.9;g.velocity.z*=.9;}if(g.timer<=0){const origin=g.mesh.position;for(let bot of bots){if(!bot.alive)continue;let distance=Math.hypot(bot.x-origin.x,bot.z-origin.z);if(distance<6&&lineClear({x:origin.x,z:origin.z,y:0},bot)){const wasAlive=bot.alive;hurt(bot,90*(1-distance/8));if(wasAlive&&!bot.alive){player.kills++;notice('Grenade elimination');}}}const blast=new T.Mesh(new T.SphereGeometry(1,10,7),new T.MeshBasicMaterial({color:'#ffae48',transparent:true,opacity:.35,depthWrite:false}));blast.position.copy(origin);blast.scale.setScalar(3);scene.add(blast);effects.push({mesh:blast,life:.3});tone(65,.35,'sawtooth',.07);g.active=false;g.mesh.visible=false;updateHUD();}}}
function toggleCrouch(){if(state!=='playing')return;crouched=!crouched;updateHUD();}
function storeSettings(){try{localStorage.setItem('ethanArenaSettings',JSON.stringify(preferences));}catch{$('settingsMessage').textContent='Settings apply for this session; device storage is unavailable.';}}
function applySettings(){const ratio=preferences.quality==='low'?1:preferences.quality==='high'?1.7:1.25;renderer.setPixelRatio(Math.min(devicePixelRatio,ratio));renderer.shadowMap.enabled=preferences.quality==='high';muted=!preferences.sound;$('sound').textContent=muted?'Sound off':'Sound on';resize();}
function openSettings(){settingsReturn=state;if(state==='playing'){pause();settingsReturn='paused';}state='settings';$('settings').hidden=false;$('quality').value=preferences.quality;$('mouseSensitivity').value=preferences.mouse;$('touchSensitivity').value=preferences.touch;$('aimAssist').checked=preferences.assist;$('soundEnabled').checked=preferences.sound;$('settingsMessage').textContent='Low graphics is best for phones. Aim speed changes apply immediately after saving.';}
function closeSettings(){preferences.quality=$('quality').value;preferences.mouse=clamp(Number($('mouseSensitivity').value)||1,.4,2);preferences.touch=clamp(Number($('touchSensitivity').value)||1,.4,2);preferences.assist=$('aimAssist').checked;preferences.sound=$('soundEnabled').checked;storeSettings();applySettings();$('settings').hidden=true;state=settingsReturn;}
$('grenade').onclick=throwGrenade;$('crouch').onclick=toggleCrouch;$('openSettings').onclick=openSettings;$('pauseSettings').onclick=openSettings;$('closeSettings').onclick=closeSettings;applySettings();

const outfitColors={lime:'#b9f55a',blue:'#50c5ee',orange:'#ffa85c'};
function previewOutfit(){outfitAvatar(player.group,outfitColors[$('outfit').value]||outfitColors.lime);$('outfitName').textContent=$('outfit').selectedOptions?.[0]?.textContent||'City Scout';}
function updateModeOptions(){const training=$('modeSelect').value==='training';$('difficulty').disabled=training;$('missionSelect').disabled=training;$('modeSummary').textContent=training?'Practice aiming · 5 reusable targets · no damage or coin rewards.':'Solo battle · 15 opponents · mission rewards enabled.';}
$('outfit').onchange=previewOutfit;$('modeSelect').onchange=updateModeOptions;previewOutfit();updateModeOptions();
$('start').disabled=false;$('start').innerHTML='ENTER THE ARENA <span>▶</span>';
