const CACHE='ethan-arena-pwa-v7-hub-integrated';
const BASE=new URL('./',self.location.href);
const FILES=['index.html','offline.html','style.css','game.js','pwa.js','three.module.js','three.core.js','GLTFLoader.js','SkeletonUtils.js','BufferGeometryUtils.js','soldier.glb','manifest.webmanifest','icon-192.png','icon-512.png','icon-maskable.png','apple-touch-icon.png','character-scout.webp'];
const ASSETS=FILES.map(file=>new URL(file,BASE).pathname);
const SHELL=new URL('index.html',BASE).pathname;
const ALLOWED=new Set([...ASSETS,BASE.pathname]);
async function notify(message){for(const client of await self.clients.matchAll({type:'window',includeUncontrolled:true}))client.postMessage(message);}
async function download(path){let failure;for(let attempt=0;attempt<3;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(new Request(path,{cache:'reload',credentials:'same-origin',signal:controller.signal}));if(!response.ok)throw new Error('HTTP '+response.status);if(path===SHELL){const html=await response.clone().text();if(!html.includes('src="game.js"')||!html.includes('ETHAN BATTLE ARENA'))throw new Error('Game page unavailable');}else if(path.endsWith('.js')){const type=response.headers.get('content-type')||'';if(type.includes('text/html'))throw new Error('Script unavailable');}else if(path.endsWith('.glb')){const bytes=await response.clone().arrayBuffer();if(new DataView(bytes).getUint32(0,true)!==0x46546c67)throw new Error('Character unavailable');}return response;}catch(error){failure=error;}finally{clearTimeout(timer);}}throw failure;}
async function precache(){const cache=await caches.open(CACHE);try{let complete=0;for(let i=0;i<ASSETS.length;i+=3){const results=await Promise.allSettled(ASSETS.slice(i,i+3).map(async path=>{await cache.put(path,await download(path));complete++;await notify({type:'OFFLINE_PROGRESS',complete,total:ASSETS.length});}));const failure=results.find(result=>result.status==='rejected');if(failure)throw failure.reason;}await notify({type:'OFFLINE_DOWNLOADED'});}catch(error){await caches.delete(CACHE);await notify({type:'OFFLINE_FAILED'});throw error;}}
self.addEventListener('install',event=>event.waitUntil(precache()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const name of await caches.keys())if(name.startsWith('ethan-arena-pwa-')&&name!==CACHE)await caches.delete(name);await self.clients.claim();await notify({type:'OFFLINE_READY'});})()));
self.addEventListener('message',event=>{if(event.data?.type==='ACTIVATE_UPDATE')self.skipWaiting();if(event.data?.type==='CACHE_STATUS')event.waitUntil((async()=>{const cache=await caches.open(CACHE);let ready=true;for(const path of ASSETS)if(!await cache.match(path)){ready=false;break;}event.ports[0]?.postMessage({ready});})());});
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url);if(request.method!=='GET'||url.origin!==self.location.origin||!ALLOWED.has(url.pathname))return;
 event.respondWith((async()=>{const cache=await caches.open(CACHE);if(request.mode==='navigate'){try{const response=await fetch(request);if(response.status>=500)throw new Error('Network unavailable');return response;}catch{return await cache.match(SHELL)||await cache.match(new URL('offline.html',BASE).pathname)||new Response('Connect to the internet to load ETHAN BATTLE ARENA.',{status:503});}}
 return await cache.match(url.pathname)||fetch(request);})());
});
