'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const palettes=[['#9be8e2','#e0f5b7','#078f9f','#043f64'],['#ffad82','#ffe1a4','#946385','#243f75'],['#181d50','#b45d9e','#154b75','#081d3e']];
const riderImage=new Image();$('start').disabled=true;const riderReady=()=>{$('start').disabled=false;};riderImage.onload=riderReady;riderImage.onerror=()=>{$('message').textContent='The rider could not load. Refresh to try again.';};riderImage.src='rider-realistic.png';
const names=['PALM COAST','SUNSET BAY','NEON LAGOON'];let route=0,w=1000,h=650,mode='menu',last=0,time=0,dist=0,score=0,hp=3,boost=100,shield=0,inv=0,x=0,riderDepth=0,jump=0,jumpV=0,spawn=0,objects=[],particles=[],combo=0,toastTime=0,muted=true,audioCtx;let best=0;try{best=+localStorage.getItem('ethan-wave-best')||0}catch{}$('best').textContent='BEST '+best;
const keys={};function resize(){w=canvas.clientWidth;h=canvas.clientHeight;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}new ResizeObserver(resize).observe(canvas);
function tone(freq=440,duration=.1){if(muted)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.05,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
function tell(t){$('toast').textContent=t;toastTime=1.5}function action(k,on){keys[k]=on;if(k==='jump'&&on&&mode==='play'&&jump===0){jumpV=2.7;tone(480)}}
window.addEventListener('keydown',e=>{const k={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',' ':'jump',Shift:'boost'}[e.key];if(k){e.preventDefault();action(k,true)}if(e.key.toLowerCase()==='p')pause()});window.addEventListener('keyup',e=>{const k={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',' ':'jump',Shift:'boost'}[e.key];if(k)action(k,false)});window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);if(mode==='play')pause()});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);action(b.dataset.key,true)};b.onpointerup=b.onpointercancel=()=>action(b.dataset.key,false)});
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=+b.dataset.route;document.querySelectorAll('[data-route]').forEach(c=>c.classList.toggle('chosen',c===b));$('routeLabel').textContent='0'+(route+1)+' · '+names[route]});
$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';tone(660)};
function start(){mode='play';dist=score=combo=jump=jumpV=x=spawn=shield=inv=0;riderDepth=0;hp=3;boost=100;objects=[];particles=[];$('overlay').style.display='none';$('pause').textContent='Pause';tone(550)}$('start').onclick=()=>mode==='pause'?resume():start();
function resume(){mode='play';$('overlay').style.display='none';$('pause').textContent='Pause'}function pause(){if(mode==='play'){mode='pause';$('overlay').style.display='flex';$('overlay').querySelector('h1').innerHTML='TAKE A<br>BREATHER<span>.</span>';$('message').textContent='Your ride is paused. Ready when you are.';$('start').innerHTML='Resume ride ▶';$('pause').textContent='Resume'}else if(mode==='pause')resume()}$('pause').onclick=pause;
function finish(){mode='over';best=Math.max(best,Math.floor(score));try{localStorage.setItem('ethan-wave-best',best)}catch{}$('best').textContent='BEST '+best;$('overlay').style.display='flex';$('overlay').querySelector('h1').innerHTML='WHAT A<br>RIDE<span>!</span>';$('message').textContent=Math.floor(score)+' points · '+Math.floor(dist)+' metres. Try a different coast or beat your record.';$('start').innerHTML='Ride again ▶';tone(140,.6)}
function project(lane,z){const depth=1-z,scale=.12+depth*depth*.95;return{x:w/2+lane*w*.36*scale,y:h*.27+depth*depth*h*.68,s:scale}}
function burst(px,py,color){for(let i=0;i<16;i++)particles.push({x:px,y:py,vx:(Math.random()-.5)*230,vy:(Math.random()-.7)*200,t:.6,c:color})}
function update(dt){time+=dt;if(mode!=='play')return;const boosting=keys.boost&&boost>1;let speed=65+(window.waveSpeed||0)+Math.min(dist/90,45)+(boosting?45:0);dist+=speed*dt;score+=speed*dt*.3;boost=Math.max(0,Math.min(100,boost+(boosting?-(35-(window.waveEfficiency||0)):12)*dt));x+=((keys.right?1:0)-(keys.left?1:0))*dt*(2.1+(window.waveHandling||0));x=Math.max(-1.1,Math.min(1.1,x));riderDepth+=((keys.up?1:0)-(keys.down?1:0))*dt*.42;riderDepth=Math.max(0,Math.min(.43,riderDepth));if(jump>0||jumpV>0){jump+=jumpV*dt;jumpV-=5.5*dt;if(jump<=0){jump=jumpV=0}}shield=Math.max(0,shield-dt);inv=Math.max(0,inv-dt);toastTime-=dt;if(toastTime<=0)$('toast').textContent='';spawn-=dt;if(spawn<=0){spawn=Math.max(.43,1.05-dist/8000);const lane=(Math.floor(Math.random()*3)-1)*.8,r=Math.random();objects.push({lane,z:1,type:r<.42?'ring':r<.54?'ramp':r<.61?'shield':r<.8?'buoy':'boat',hit:false});if(r<.42)objects.push({lane,z:1.12,type:'ring',hit:false})}
for(const o of objects){o.z-=dt*speed/230;if(o.type==='boat')o.lane+=Math.sin(time*1.2+o.z)*dt*.18;if(!o.hit&&o.z<riderDepth+.065&&o.z>riderDepth-.12){if(Math.abs(x-o.lane)<.27){o.hit=true;const p=project(o.lane,riderDepth);if(o.type==='ring'){window.waveRing?.();score+=100+combo*10;combo++;tone(660+Math.min(combo,8)*40);burst(p.x,p.y-jump*95,'#ffde58');if(combo%5===0)tell(combo+' RING STREAK!')}else if(o.type==='shield'){shield=8+(window.waveShield||0);tell('SHIELD · 8 SECONDS');tone(880,.3)}else if(o.type==='ramp'){window.waveRamp?.();jumpV=3.8;score+=250;tell('BIG AIR! +250');tone(440,.3)}else if(jump>.28){score+=150;tell('CLEAN JUMP! +150')}else if(inv===0){if(shield>0){shield=0;tell('SHIELD SAVED YOU!')}else{hp--;window.waveHit?.();combo=0;inv=1.7;tell('WATCH THE WATER!');tone(100,.25);burst(p.x,p.y,'#fff');if(hp<=0)finish()}}}}}objects=objects.filter(o=>o.z>-.2);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.t-=dt}particles=particles.filter(p=>p.t>0);$('score').textContent=Math.floor(score).toString().padStart(5,'0');$('distance').textContent=Math.floor(dist)+' m';$('hearts').textContent='♥ '.repeat(hp)+'♡ '.repeat(3-hp);$('boostBar').style.width=boost+'%';$('shieldLabel').textContent=shield>0?'SHIELD '+Math.ceil(shield)+'s':'SHIELD OFF'}
function ellipse(a,b,c,d,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(a,b,c,d,0,0,Math.PI*2);ctx.fill()}function line(points,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke()}
function draw(){const pal=palettes[route];let g=ctx.createLinearGradient(0,0,0,h*.34);g.addColorStop(0,pal[0]);g.addColorStop(1,pal[1]);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ellipse(w*.78,h*.13,h*.063,h*.063,route===2?'#b3eaff':'#fff1bd');ctx.fillStyle=route===2?'#153b52':'#326a6b';ctx.beginPath();ctx.moveTo(0,h*.3);for(let i=0;i<=12;i++)ctx.lineTo(i*w/12,h*(.23+Math.sin(i*2.1)*.035));ctx.lineTo(w,h*.4);ctx.lineTo(0,h*.4);ctx.fill();g=ctx.createLinearGradient(0,h*.28,0,h);g.addColorStop(0,pal[2]);g.addColorStop(1,pal[3]);ctx.fillStyle=g;ctx.fillRect(0,h*.29,w,h);ctx.fillStyle=route===2?'#142e36':'#c8c795';ctx.beginPath();ctx.moveTo(0,h*.28);ctx.lineTo(w*.36,h*.29);ctx.lineTo(w*.02,h);ctx.lineTo(0,h);ctx.fill();ctx.beginPath();ctx.moveTo(w,h*.28);ctx.lineTo(w*.64,h*.29);ctx.lineTo(w*.98,h);ctx.lineTo(w,h);ctx.fill();
for(let i=0;i<38;i++){let z=(i/38+time*(mode==='play'?.22:.05))%1;const p=project(0,1-z);ctx.strokeStyle=route===2?'#8e71f933':'#9af3f13d';ctx.lineWidth=1+z*2;ctx.beginPath();ctx.moveTo(w/2-w*.45*p.s,p.y);ctx.bezierCurveTo(w*.4,p.y-3,w*.6,p.y+3,w/2+w*.45*p.s,p.y);ctx.stroke()}
for(const lane of [-1.35,1.35])for(let i=0;i<8;i++){const p=project(lane,(i/8+time*.12)%1);ellipse(p.x,p.y,3+9*p.s,2+4*p.s,'#f4f2cf');}
objects.slice().sort((a,b)=>b.z-a.z).forEach(o=>{if(o.hit)return;const p=project(o.lane,o.z),s=p.s*40;ctx.save();ctx.translate(p.x,p.y);ellipse(0,5,s*.7,s*.14,'#022d4f55');if(o.type==='ring'){ctx.strokeStyle='#ffdd58';ctx.lineWidth=6*p.s;ctx.beginPath();ctx.ellipse(0,-s*.55,s*.34,s*.47,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#fff5b4';ctx.lineWidth=2*p.s;ctx.stroke()}else if(o.type==='shield'){ellipse(0,-s*.5,s*.35,s*.35,'#66ffff');ctx.fillStyle='#075572';ctx.font='bold '+s*.5+'px Arial';ctx.textAlign='center';ctx.fillText('S',0,-s*.32)}else if(o.type==='ramp'){ctx.fillStyle='#ffd65b';ctx.beginPath();ctx.moveTo(-s*.6,0);ctx.lineTo(s*.6,0);ctx.lineTo(s*.5,-s*.5);ctx.lineTo(-s*.5,-s*.5);ctx.fill();line([[-s*.3,-s*.1],[0,-s*.38],[s*.3,-s*.1]],'#8d5c18',3*p.s)}else if(o.type==='buoy'){ctx.fillStyle='#ff7254';ctx.fillRect(-s*.25,-s*.85,s*.5,s*.85);ctx.fillStyle='#fff5dd';ctx.fillRect(-s*.25,-s*.55,s*.5,s*.18);ellipse(0,0,s*.4,s*.12,'#d75039')}else{ctx.fillStyle='#f3f4eb';ctx.beginPath();ctx.moveTo(-s*.55,-s*.15);ctx.lineTo(-s*.4,-s*.7);ctx.lineTo(s*.4,-s*.7);ctx.lineTo(s*.55,-s*.15);ctx.lineTo(0,s*.22);ctx.fill();ctx.fillStyle='#ff7158';ctx.fillRect(-s*.3,-s*.95,s*.6,s*.25);ctx.fillStyle='#123f57';ctx.fillRect(-s*.25,-s*.65,s*.5,s*.3)}ctx.restore()});
const p=project(mode==='menu'?.55:x,riderDepth),py=p.y-jump*95;ellipse(p.x,p.y+10,32,8,'#02243166');for(let i=0;i<12;i++){let v=(i/12+time*2)%1;ellipse(p.x+(Math.sin(i*4)*16)*(1+v*2),p.y+10+v*65,2+v*2,5+v*4,'#d4fff96b')}
ctx.save();ctx.translate(p.x,py);ctx.rotate(((keys.right?1:0)-(keys.left?1:0))*.15+(window.waveSpin||0));if(inv>0&&Math.sin(time*35)>0)ctx.globalAlpha=.4;if(shield>0){ctx.strokeStyle='#63ffff';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,-32,45,66,0,0,Math.PI*2);ctx.stroke()}if(riderImage.complete&&riderImage.naturalWidth){const size=Math.min(180,Math.max(135,w*.17))*p.s/1.07;const ratio=riderImage.naturalWidth/riderImage.naturalHeight;const bob=jump>0?0:Math.sin(time*9)*1.6;ctx.filter=window.waveRiderFilter||'none';ctx.drawImage(riderImage,-size*ratio/2,-size*.79+bob,size*ratio,size);} ctx.restore();particles.forEach(p=>{ctx.globalAlpha=p.t/.6;ellipse(p.x,p.y,3,3,p.c)});ctx.globalAlpha=1;if(mode==='pause'){ctx.fillStyle='#041c3440';ctx.fillRect(0,0,w,h)}}
function frame(t){const dt=Math.min((t-last)/1000,.04)||.016;last=t;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
